/**
 * ARCHITECT repo manifest — GENERATED FILE. DO NOT EDIT BY HAND.
 *
 * Regenerated by scripts/build-architect-manifest.ts on every
 * trust-radar build. Committed to git so the Worker has a
 * deterministic repo inventory at runtime without filesystem access.
 */

import type { RepoInventory } from "./types";

export const REPO_MANIFEST: RepoInventory = {
  "collected_at": "build-time",
  "agents": [
    {
      "name": "analyst",
      "path": "packages/trust-radar/src/agents/analyst.ts",
      "entrypoint": "analystAgent",
      "triggers": [
        "cron"
      ],
      "reads": [
        "DB",
        "brand_threat_assessments",
        "brands",
        "geopolitical_campaign_links",
        "geopolitical_campaigns",
        "monitored_brands",
        "social_mentions",
        "threats"
      ],
      "writes": [
        "agent_outputs",
        "brands",
        "threats"
      ],
      "ai_models_referenced": [],
      "loc": 769,
      "last_modified": "2026-04-09T18:00:39.763Z"
    },
    {
      "name": "cartographer",
      "path": "packages/trust-radar/src/agents/cartographer.ts",
      "entrypoint": "cartographerAgent",
      "triggers": [
        "cron",
        "queue"
      ],
      "reads": [
        "CACHE",
        "DB",
        "brands",
        "dmarc_report_records",
        "geopolitical_campaign_links",
        "geopolitical_campaigns",
        "hosting_providers",
        "threats"
      ],
      "writes": [
        "SET",
        "agent_events",
        "alerts",
        "brands",
        "dmarc_report_records",
        "hosting_providers",
        "provider_threat_stats",
        "threats"
      ],
      "ai_models_referenced": [],
      "loc": 741,
      "last_modified": "2026-04-09T18:00:39.766Z"
    },
    {
      "name": "curator",
      "path": "packages/trust-radar/src/agents/curator.ts",
      "entrypoint": "curatorAgent",
      "triggers": [
        "queue"
      ],
      "reads": [
        "DB",
        "brands",
        "social_profiles"
      ],
      "writes": [
        "SET",
        "brands",
        "social_profiles",
        "threats"
      ],
      "ai_models_referenced": [],
      "loc": 163,
      "last_modified": "2026-04-09T18:00:39.766Z"
    },
    {
      "name": "flightControl",
      "path": "packages/trust-radar/src/agents/flightControl.ts",
      "entrypoint": "flightControlAgent",
      "triggers": [
        "cron"
      ],
      "reads": [
        "CACHE",
        "CERTSTREAM_MONITOR",
        "DB",
        "agent_outputs",
        "agent_runs",
        "backlog_history",
        "brands",
        "feed_configs",
        "feed_status",
        "social_mentions",
        "threats"
      ],
      "writes": [
        "agent_activity_log",
        "backlog_history"
      ],
      "ai_models_referenced": [],
      "loc": 752,
      "last_modified": "2026-04-09T18:00:39.766Z"
    },
    {
      "name": "narrator",
      "path": "packages/trust-radar/src/agents/narrator.ts",
      "entrypoint": "generateThreatNarrative",
      "triggers": [],
      "reads": [
        "DB",
        "brand_profiles",
        "brands",
        "ct_certificates",
        "lookalike_domains",
        "social_monitor_results",
        "threats"
      ],
      "writes": [
        "threat_narratives"
      ],
      "ai_models_referenced": [
        "claude-haiku-4-5-20251001"
      ],
      "loc": 323,
      "last_modified": "2026-04-09T18:00:39.766Z"
    },
    {
      "name": "nexus",
      "path": "packages/trust-radar/src/agents/nexus.ts",
      "entrypoint": "nexusAgent",
      "triggers": [
        "cron",
        "queue"
      ],
      "reads": [
        "DB",
        "hosting_providers",
        "threats"
      ],
      "writes": [
        "agent_events",
        "agent_runs",
        "hosting_providers",
        "infrastructure_clusters",
        "threats"
      ],
      "ai_models_referenced": [],
      "loc": 281,
      "last_modified": "2026-04-09T18:00:39.766Z"
    },
    {
      "name": "observer",
      "path": "packages/trust-radar/src/agents/observer.ts",
      "entrypoint": "observerAgent",
      "triggers": [
        "cron"
      ],
      "reads": [
        "DB",
        "agent_outputs",
        "brand_threat_assessments",
        "brands",
        "campaigns",
        "ct_certificates",
        "email_security_scans",
        "geopolitical_campaign_links",
        "geopolitical_campaigns",
        "hosting_providers",
        "lookalike_domains",
        "social_mentions",
        "social_profiles",
        "spam_trap_captures",
        "threat_narratives",
        "threat_signals",
        "threats"
      ],
      "writes": [
        "agent_outputs"
      ],
      "ai_models_referenced": [],
      "loc": 842,
      "last_modified": "2026-04-09T18:00:39.766Z"
    },
    {
      "name": "pathfinder",
      "path": "packages/trust-radar/src/agents/pathfinder.ts",
      "entrypoint": "pathfinderAgent",
      "triggers": [
        "cron"
      ],
      "reads": [
        "CACHE",
        "DB",
        "brand_threat_assessments",
        "brands",
        "email_security_scans",
        "org_brands",
        "phishing_pattern_signals",
        "sales_leads",
        "spam_trap_captures",
        "threat_signals",
        "threats"
      ],
      "writes": [],
      "ai_models_referenced": [
        "claude-haiku-4-5-20251001"
      ],
      "loc": 573,
      "last_modified": "2026-04-09T18:00:39.766Z"
    },
    {
      "name": "seed-strategist",
      "path": "packages/trust-radar/src/agents/seed-strategist.ts",
      "entrypoint": "seedStrategistAgent",
      "triggers": [
        "cron"
      ],
      "reads": [
        "DB",
        "brands",
        "seed_campaigns",
        "spam_trap_captures"
      ],
      "writes": [
        "agent_outputs",
        "seed_addresses",
        "seed_campaigns"
      ],
      "ai_models_referenced": [
        "claude-haiku-4-5-20251001"
      ],
      "loc": 215,
      "last_modified": "2026-04-09T18:00:39.768Z"
    },
    {
      "name": "sentinel",
      "path": "packages/trust-radar/src/agents/sentinel.ts",
      "entrypoint": "sentinelAgent",
      "triggers": [
        "queue"
      ],
      "reads": [
        "DB",
        "brand_profiles",
        "brands",
        "monitored_brands",
        "social_monitor_results",
        "social_profiles",
        "threats"
      ],
      "writes": [
        "social_monitor_results",
        "threats"
      ],
      "ai_models_referenced": [
        "claude-haiku-4-5-20251001"
      ],
      "loc": 519,
      "last_modified": "2026-04-09T18:00:39.768Z"
    },
    {
      "name": "sparrow",
      "path": "packages/trust-radar/src/agents/sparrow.ts",
      "entrypoint": "sparrowAgent",
      "triggers": [
        "cron"
      ],
      "reads": [
        "DB",
        "brands",
        "social_mentions",
        "social_profiles",
        "takedown_evidence",
        "takedown_providers",
        "takedown_requests",
        "url_scan_results"
      ],
      "writes": [
        "takedown_evidence",
        "takedown_requests",
        "url_scan_results"
      ],
      "ai_models_referenced": [],
      "loc": 417,
      "last_modified": "2026-04-09T18:00:39.768Z"
    },
    {
      "name": "strategist",
      "path": "packages/trust-radar/src/agents/strategist.ts",
      "entrypoint": "strategistAgent",
      "triggers": [
        "cron"
      ],
      "reads": [
        "DB",
        "brands",
        "campaigns",
        "hosting_providers",
        "threats"
      ],
      "writes": [
        "agent_outputs",
        "campaigns",
        "threats"
      ],
      "ai_models_referenced": [],
      "loc": 477,
      "last_modified": "2026-04-09T18:00:39.768Z"
    },
    {
      "name": "trustbot",
      "path": "packages/trust-radar/src/agents/trustbot.ts",
      "entrypoint": "trustbotAgent",
      "triggers": [
        "manual"
      ],
      "reads": [
        "DB",
        "feed_schedules",
        "radar_agent_runs",
        "threats"
      ],
      "writes": [],
      "ai_models_referenced": [],
      "loc": 164,
      "last_modified": "2026-04-09T18:00:39.768Z"
    },
    {
      "name": "watchdog",
      "path": "packages/trust-radar/src/agents/watchdog.ts",
      "entrypoint": "watchdogAgent",
      "triggers": [
        "queue"
      ],
      "reads": [
        "DB",
        "brands",
        "social_mentions"
      ],
      "writes": [
        "social_mentions",
        "threats"
      ],
      "ai_models_referenced": [
        "claude-haiku-4-5-20251001"
      ],
      "loc": 367,
      "last_modified": "2026-04-09T18:00:39.768Z"
    }
  ],
  "feeds": [
    {
      "name": "abuseipdb",
      "path": "packages/trust-radar/src/feeds/abuseipdb.ts",
      "source_type": "http",
      "schedule": null,
      "loc": 242,
      "last_modified": "2026-04-09T18:00:39.781Z"
    },
    {
      "name": "blocklistde",
      "path": "packages/trust-radar/src/feeds/blocklistde.ts",
      "source_type": "http",
      "schedule": null,
      "loc": 98,
      "last_modified": "2026-04-09T18:00:39.781Z"
    },
    {
      "name": "c2intelfeeds",
      "path": "packages/trust-radar/src/feeds/c2intelfeeds.ts",
      "source_type": "http",
      "schedule": null,
      "loc": 169,
      "last_modified": "2026-04-09T18:00:39.781Z"
    },
    {
      "name": "c2tracker",
      "path": "packages/trust-radar/src/feeds/c2tracker.ts",
      "source_type": "http",
      "schedule": null,
      "loc": 122,
      "last_modified": "2026-04-09T18:00:39.784Z"
    },
    {
      "name": "certstream",
      "path": "packages/trust-radar/src/feeds/certstream.ts",
      "source_type": "http",
      "schedule": null,
      "loc": 216,
      "last_modified": "2026-04-09T18:00:39.784Z"
    },
    {
      "name": "cins_army",
      "path": "packages/trust-radar/src/feeds/cins_army.ts",
      "source_type": "unknown",
      "schedule": null,
      "loc": 103,
      "last_modified": "2026-04-09T18:00:39.784Z"
    },
    {
      "name": "circlPassiveDns",
      "path": "packages/trust-radar/src/feeds/circlPassiveDns.ts",
      "source_type": "http",
      "schedule": null,
      "loc": 192,
      "last_modified": "2026-04-09T18:00:39.784Z"
    },
    {
      "name": "cisa_iran_iocs",
      "path": "packages/trust-radar/src/feeds/cisa_iran_iocs.ts",
      "source_type": "unknown",
      "schedule": null,
      "loc": 194,
      "last_modified": "2026-04-09T18:00:39.784Z"
    },
    {
      "name": "cisa_kev",
      "path": "packages/trust-radar/src/feeds/cisa_kev.ts",
      "source_type": "unknown",
      "schedule": null,
      "loc": 93,
      "last_modified": "2026-04-09T18:00:39.784Z"
    },
    {
      "name": "cloudflare_email",
      "path": "packages/trust-radar/src/feeds/cloudflare_email.ts",
      "source_type": "api",
      "schedule": null,
      "loc": 134,
      "last_modified": "2026-04-09T18:00:39.784Z"
    },
    {
      "name": "cloudflare_scanner",
      "path": "packages/trust-radar/src/feeds/cloudflare_scanner.ts",
      "source_type": "api",
      "schedule": null,
      "loc": 286,
      "last_modified": "2026-04-09T18:00:39.784Z"
    },
    {
      "name": "disposableEmail",
      "path": "packages/trust-radar/src/feeds/disposableEmail.ts",
      "source_type": "http",
      "schedule": null,
      "loc": 97,
      "last_modified": "2026-04-09T18:00:39.784Z"
    },
    {
      "name": "dshield",
      "path": "packages/trust-radar/src/feeds/dshield.ts",
      "source_type": "http",
      "schedule": null,
      "loc": 64,
      "last_modified": "2026-04-09T18:00:39.784Z"
    },
    {
      "name": "emergingThreats",
      "path": "packages/trust-radar/src/feeds/emergingThreats.ts",
      "source_type": "http",
      "schedule": null,
      "loc": 90,
      "last_modified": "2026-04-09T18:00:39.784Z"
    },
    {
      "name": "feodo",
      "path": "packages/trust-radar/src/feeds/feodo.ts",
      "source_type": "http",
      "schedule": null,
      "loc": 41,
      "last_modified": "2026-04-09T18:00:39.784Z"
    },
    {
      "name": "github",
      "path": "packages/trust-radar/src/feeds/github.ts",
      "source_type": "api",
      "schedule": null,
      "loc": 407,
      "last_modified": "2026-04-09T18:00:39.784Z"
    },
    {
      "name": "googleSafeBrowsing",
      "path": "packages/trust-radar/src/feeds/googleSafeBrowsing.ts",
      "source_type": "http",
      "schedule": null,
      "loc": 271,
      "last_modified": "2026-04-09T18:00:39.788Z"
    },
    {
      "name": "greynoise",
      "path": "packages/trust-radar/src/feeds/greynoise.ts",
      "source_type": "http",
      "schedule": null,
      "loc": 264,
      "last_modified": "2026-04-09T18:00:39.788Z"
    },
    {
      "name": "hibp",
      "path": "packages/trust-radar/src/feeds/hibp.ts",
      "source_type": "http",
      "schedule": null,
      "loc": 161,
      "last_modified": "2026-04-09T18:00:39.788Z"
    },
    {
      "name": "malwarebazaar",
      "path": "packages/trust-radar/src/feeds/malwarebazaar.ts",
      "source_type": "unknown",
      "schedule": null,
      "loc": 99,
      "last_modified": "2026-04-09T18:00:39.788Z"
    },
    {
      "name": "mastodon",
      "path": "packages/trust-radar/src/feeds/mastodon.ts",
      "source_type": "http",
      "schedule": null,
      "loc": 330,
      "last_modified": "2026-04-09T18:00:39.788Z"
    },
    {
      "name": "nrd_hagezi",
      "path": "packages/trust-radar/src/feeds/nrd_hagezi.ts",
      "source_type": "http",
      "schedule": null,
      "loc": 247,
      "last_modified": "2026-04-09T18:00:39.788Z"
    },
    {
      "name": "openphish",
      "path": "packages/trust-radar/src/feeds/openphish.ts",
      "source_type": "http",
      "schedule": null,
      "loc": 44,
      "last_modified": "2026-04-09T18:00:39.788Z"
    },
    {
      "name": "otx_alienvault",
      "path": "packages/trust-radar/src/feeds/otx_alienvault.ts",
      "source_type": "unknown",
      "schedule": null,
      "loc": 98,
      "last_modified": "2026-04-09T18:00:39.788Z"
    },
    {
      "name": "phishdestroy",
      "path": "packages/trust-radar/src/feeds/phishdestroy.ts",
      "source_type": "http",
      "schedule": null,
      "loc": 48,
      "last_modified": "2026-04-09T18:00:39.788Z"
    },
    {
      "name": "phishtank",
      "path": "packages/trust-radar/src/feeds/phishtank.ts",
      "source_type": "http",
      "schedule": null,
      "loc": 73,
      "last_modified": "2026-04-09T18:00:39.788Z"
    },
    {
      "name": "reddit",
      "path": "packages/trust-radar/src/feeds/reddit.ts",
      "source_type": "api",
      "schedule": null,
      "loc": 353,
      "last_modified": "2026-04-09T18:00:39.788Z"
    },
    {
      "name": "seclookup",
      "path": "packages/trust-radar/src/feeds/seclookup.ts",
      "source_type": "api",
      "schedule": null,
      "loc": 270,
      "last_modified": "2026-04-09T18:00:39.788Z"
    },
    {
      "name": "spamhausDbl",
      "path": "packages/trust-radar/src/feeds/spamhausDbl.ts",
      "source_type": "http",
      "schedule": null,
      "loc": 254,
      "last_modified": "2026-04-09T18:00:39.792Z"
    },
    {
      "name": "spamhausDrop",
      "path": "packages/trust-radar/src/feeds/spamhausDrop.ts",
      "source_type": "http",
      "schedule": null,
      "loc": 144,
      "last_modified": "2026-04-09T18:00:39.792Z"
    },
    {
      "name": "sslbl",
      "path": "packages/trust-radar/src/feeds/sslbl.ts",
      "source_type": "http",
      "schedule": null,
      "loc": 99,
      "last_modified": "2026-04-09T18:00:39.792Z"
    },
    {
      "name": "surbl",
      "path": "packages/trust-radar/src/feeds/surbl.ts",
      "source_type": "http",
      "schedule": null,
      "loc": 205,
      "last_modified": "2026-04-09T18:00:39.792Z"
    },
    {
      "name": "telegram",
      "path": "packages/trust-radar/src/feeds/telegram.ts",
      "source_type": "http",
      "schedule": null,
      "loc": 406,
      "last_modified": "2026-04-09T18:00:39.792Z"
    },
    {
      "name": "threatfox",
      "path": "packages/trust-radar/src/feeds/threatfox.ts",
      "source_type": "unknown",
      "schedule": null,
      "loc": 98,
      "last_modified": "2026-04-09T18:00:39.792Z"
    },
    {
      "name": "torExitNodes",
      "path": "packages/trust-radar/src/feeds/torExitNodes.ts",
      "source_type": "http",
      "schedule": null,
      "loc": 88,
      "last_modified": "2026-04-09T18:00:39.792Z"
    },
    {
      "name": "typosquat_scanner",
      "path": "packages/trust-radar/src/feeds/typosquat_scanner.ts",
      "source_type": "http",
      "schedule": null,
      "loc": 219,
      "last_modified": "2026-04-09T18:00:39.792Z"
    },
    {
      "name": "urlhaus",
      "path": "packages/trust-radar/src/feeds/urlhaus.ts",
      "source_type": "unknown",
      "schedule": null,
      "loc": 82,
      "last_modified": "2026-04-09T18:00:39.792Z"
    },
    {
      "name": "virustotal",
      "path": "packages/trust-radar/src/feeds/virustotal.ts",
      "source_type": "api",
      "schedule": null,
      "loc": 211,
      "last_modified": "2026-04-09T18:00:39.792Z"
    }
  ],
  "crons": [
    {
      "pattern": "0 * * * *",
      "handler_path": "packages/trust-radar/src/index.ts",
      "agents_invoked": [
        "analyst",
        "cartographer",
        "flightControl",
        "nexus",
        "observer",
        "pathfinder",
        "seed-strategist",
        "sparrow",
        "strategist"
      ]
    }
  ],
  "workers": [
    {
      "name": "trust-radar",
      "path": "packages/trust-radar/src/index.ts",
      "bindings": [
        "ARCHITECT_BUNDLES",
        "AUDIT_DB",
        "CACHE",
        "CARTOGRAPHER_BACKFILL",
        "CERTSTREAM_MONITOR",
        "DB",
        "NEXUS_RUN",
        "THREAT_PUSH_HUB"
      ]
    }
  ],
  "totals": {
    "agents": 14,
    "feeds": 38,
    "crons": 1,
    "workers": 1
  }
};
