/**
 * ARCHITECT repo manifest — GENERATED FILE. DO NOT EDIT BY HAND.
 *
 * Regenerated by scripts/build-architect-manifest.ts on every
 * trust-radar build. Committed to git so the Worker has a
 * deterministic repo inventory at runtime without filesystem access.
 */

import type { RepoInventory } from "./types";

export const REPO_MANIFEST: RepoInventory = {
  "collected_at": "build-time",
  "agents": [
    {
      "name": "admin-classify",
      "path": "packages/trust-radar/src/agents/admin-classify.ts",
      "entrypoint": "adminClassifyAgent",
      "triggers": [
        "http"
      ],
      "reads": [],
      "writes": [],
      "ai_models_referenced": [],
      "loc": 208,
      "last_modified": "2026-05-04T17:56:39.951Z"
    },
    {
      "name": "analyst",
      "path": "packages/trust-radar/src/agents/analyst.ts",
      "entrypoint": "analystAgent",
      "triggers": [
        "cron"
      ],
      "reads": [
        "DB",
        "app_store_listings",
        "brand_threat_assessments",
        "brands",
        "dark_web_mentions",
        "geopolitical_campaign_links",
        "geopolitical_campaigns",
        "monitored_brands",
        "social_mentions",
        "social_profiles",
        "threats"
      ],
      "writes": [
        "agent_outputs",
        "brands",
        "threats"
      ],
      "ai_models_referenced": [],
      "loc": 1075,
      "last_modified": "2026-05-06T21:26:51.735Z"
    },
    {
      "name": "appStoreMonitor",
      "path": "packages/trust-radar/src/agents/appStoreMonitor.ts",
      "entrypoint": "appStoreMonitorAgent",
      "triggers": [
        "cron"
      ],
      "reads": [],
      "writes": [],
      "ai_models_referenced": [],
      "loc": 63,
      "last_modified": "2026-05-04T17:56:39.953Z"
    },
    {
      "name": "attributor",
      "path": "packages/trust-radar/src/agents/attributor.ts",
      "entrypoint": "attributorAgent",
      "triggers": [
        "cron"
      ],
      "reads": [
        "DB",
        "infrastructure_clusters",
        "threats"
      ],
      "writes": [
        "infrastructure_clusters"
      ],
      "ai_models_referenced": [],
      "loc": 256,
      "last_modified": "2026-05-06T18:46:42.160Z"
    },
    {
      "name": "auto-seeder",
      "path": "packages/trust-radar/src/agents/auto-seeder.ts",
      "entrypoint": "autoSeederAgent",
      "triggers": [
        "cron"
      ],
      "reads": [],
      "writes": [],
      "ai_models_referenced": [],
      "loc": 106,
      "last_modified": "2026-05-04T17:56:39.958Z"
    },
    {
      "name": "brand-analysis",
      "path": "packages/trust-radar/src/agents/brand-analysis.ts",
      "entrypoint": "brandAnalysisAgent",
      "triggers": [
        "http"
      ],
      "reads": [],
      "writes": [],
      "ai_models_referenced": [],
      "loc": 247,
      "last_modified": "2026-05-04T17:56:39.958Z"
    },
    {
      "name": "brand-deep-scan",
      "path": "packages/trust-radar/src/agents/brand-deep-scan.ts",
      "entrypoint": "brandDeepScanAgent",
      "triggers": [
        "http"
      ],
      "reads": [],
      "writes": [],
      "ai_models_referenced": [],
      "loc": 246,
      "last_modified": "2026-05-04T17:56:39.958Z"
    },
    {
      "name": "brand-enricher",
      "path": "packages/trust-radar/src/agents/brand-enricher.ts",
      "entrypoint": "brandEnricherAgent",
      "triggers": [
        "http"
      ],
      "reads": [],
      "writes": [],
      "ai_models_referenced": [],
      "loc": 143,
      "last_modified": "2026-05-04T17:56:39.958Z"
    },
    {
      "name": "brand-report",
      "path": "packages/trust-radar/src/agents/brand-report.ts",
      "entrypoint": "brandReportAgent",
      "triggers": [
        "http"
      ],
      "reads": [],
      "writes": [],
      "ai_models_referenced": [],
      "loc": 245,
      "last_modified": "2026-05-04T17:56:39.958Z"
    },
    {
      "name": "cartographer",
      "path": "packages/trust-radar/src/agents/cartographer.ts",
      "entrypoint": "cartographerAgent",
      "triggers": [
        "cron",
        "queue"
      ],
      "reads": [
        "CACHE",
        "DB",
        "brands",
        "dmarc_report_records",
        "geopolitical_campaign_links",
        "geopolitical_campaigns",
        "hosting_providers",
        "threats"
      ],
      "writes": [
        "SET",
        "agent_events",
        "alerts",
        "brands",
        "dmarc_report_records",
        "hosting_providers",
        "merges",
        "provider_threat_stats",
        "threats"
      ],
      "ai_models_referenced": [],
      "loc": 1076,
      "last_modified": "2026-05-06T18:46:42.160Z"
    },
    {
      "name": "cube-healer",
      "path": "packages/trust-radar/src/agents/cube-healer.ts",
      "entrypoint": "cubeHealerAgent",
      "triggers": [
        "cron"
      ],
      "reads": [
        "CACHE",
        "DB",
        "threats"
      ],
      "writes": [
        "threat_cube_brand",
        "threat_cube_geo",
        "threat_cube_provider",
        "threat_cube_status"
      ],
      "ai_models_referenced": [],
      "loc": 302,
      "last_modified": "2026-05-04T17:56:39.958Z"
    },
    {
      "name": "curator",
      "path": "packages/trust-radar/src/agents/curator.ts",
      "entrypoint": "curatorAgent",
      "triggers": [
        "queue"
      ],
      "reads": [
        "DB",
        "brands",
        "social_profiles"
      ],
      "writes": [
        "SET",
        "brands",
        "social_profiles",
        "threats"
      ],
      "ai_models_referenced": [],
      "loc": 180,
      "last_modified": "2026-05-04T17:56:39.958Z"
    },
    {
      "name": "darkWebMonitor",
      "path": "packages/trust-radar/src/agents/darkWebMonitor.ts",
      "entrypoint": "darkWebMonitorAgent",
      "triggers": [
        "cron"
      ],
      "reads": [],
      "writes": [],
      "ai_models_referenced": [],
      "loc": 63,
      "last_modified": "2026-05-04T17:56:39.958Z"
    },
    {
      "name": "evidence-assembler",
      "path": "packages/trust-radar/src/agents/evidence-assembler.ts",
      "entrypoint": "evidenceAssemblerAgent",
      "triggers": [
        "http"
      ],
      "reads": [],
      "writes": [],
      "ai_models_referenced": [],
      "loc": 304,
      "last_modified": "2026-05-04T17:56:39.958Z"
    },
    {
      "name": "flightControl",
      "path": "packages/trust-radar/src/agents/flightControl.ts",
      "entrypoint": "flightControlAgent",
      "triggers": [
        "cron"
      ],
      "reads": [
        "CACHE",
        "CERTSTREAM_MONITOR",
        "DB",
        "agent_configs",
        "agent_outputs",
        "agent_runs",
        "backlog_history",
        "brands",
        "feed_configs",
        "feed_pull_history",
        "feed_status",
        "geo_ip_refresh_log",
        "incidents",
        "push_subscriptions",
        "social_mentions",
        "threat_briefings",
        "threats"
      ],
      "writes": [
        "agent_activity_log",
        "agent_runs",
        "backlog_history",
        "geo_ip_refresh_log",
        "incident_updates",
        "push_subscriptions"
      ],
      "ai_models_referenced": [],
      "loc": 1814,
      "last_modified": "2026-05-07T00:44:29.167Z"
    },
    {
      "name": "geo-campaign-assessment",
      "path": "packages/trust-radar/src/agents/geo-campaign-assessment.ts",
      "entrypoint": "geoCampaignAssessmentAgent",
      "triggers": [
        "http"
      ],
      "reads": [],
      "writes": [],
      "ai_models_referenced": [],
      "loc": 254,
      "last_modified": "2026-05-04T17:56:39.958Z"
    },
    {
      "name": "geoip-refresh",
      "path": "packages/trust-radar/src/agents/geoip-refresh.ts",
      "entrypoint": "geoipRefreshAgent",
      "triggers": [
        "cron"
      ],
      "reads": [
        "CACHE",
        "geo_ip_refresh_log"
      ],
      "writes": [
        "geo_ip_refresh_log"
      ],
      "ai_models_referenced": [],
      "loc": 597,
      "last_modified": "2026-05-06T18:46:42.164Z"
    },
    {
      "name": "honeypot-generator",
      "path": "packages/trust-radar/src/agents/honeypot-generator.ts",
      "entrypoint": "honeypotGeneratorAgent",
      "triggers": [
        "http"
      ],
      "reads": [],
      "writes": [],
      "ai_models_referenced": [],
      "loc": 206,
      "last_modified": "2026-05-04T17:56:39.962Z"
    },
    {
      "name": "lookalike-scanner",
      "path": "packages/trust-radar/src/agents/lookalike-scanner.ts",
      "entrypoint": "lookalikeScannerAgent",
      "triggers": [
        "cron"
      ],
      "reads": [],
      "writes": [],
      "ai_models_referenced": [],
      "loc": 73,
      "last_modified": "2026-05-04T17:56:39.962Z"
    },
    {
      "name": "narrator",
      "path": "packages/trust-radar/src/agents/narrator.ts",
      "entrypoint": "narratorAgent",
      "triggers": [
        "cron"
      ],
      "reads": [
        "DB",
        "app_store_listings",
        "brands",
        "ct_certificates",
        "dark_web_mentions",
        "lookalike_domains",
        "social_monitor_results",
        "threat_narratives",
        "threats"
      ],
      "writes": [
        "threat_narratives"
      ],
      "ai_models_referenced": [],
      "loc": 481,
      "last_modified": "2026-05-07T14:52:41.416Z"
    },
    {
      "name": "news-watcher",
      "path": "packages/trust-radar/src/agents/news-watcher.ts",
      "entrypoint": "newsWatcherAgent",
      "triggers": [
        "cron"
      ],
      "reads": [
        "DB",
        "geopolitical_campaigns",
        "news_articles"
      ],
      "writes": [
        "SET",
        "geopolitical_campaigns",
        "news_articles"
      ],
      "ai_models_referenced": [],
      "loc": 314,
      "last_modified": "2026-05-06T18:46:42.164Z"
    },
    {
      "name": "nexus",
      "path": "packages/trust-radar/src/agents/nexus.ts",
      "entrypoint": "nexusAgent",
      "triggers": [
        "cron",
        "queue"
      ],
      "reads": [
        "DB",
        "app_store_listings",
        "brands",
        "dark_web_mentions",
        "hosting_providers",
        "threats"
      ],
      "writes": [
        "SET",
        "agent_events",
        "agent_runs",
        "hosting_providers",
        "infrastructure_clusters",
        "threats"
      ],
      "ai_models_referenced": [],
      "loc": 602,
      "last_modified": "2026-05-06T21:30:19.443Z"
    },
    {
      "name": "notification_narrator",
      "path": "packages/trust-radar/src/agents/notification_narrator.ts",
      "entrypoint": "notificationNarratorAgent",
      "triggers": [
        "cron"
      ],
      "reads": [
        "DB",
        "notification_preferences_v2",
        "notifications",
        "users"
      ],
      "writes": [],
      "ai_models_referenced": [],
      "loc": 187,
      "last_modified": "2026-05-04T17:56:39.962Z"
    },
    {
      "name": "observer",
      "path": "packages/trust-radar/src/agents/observer.ts",
      "entrypoint": "observerAgent",
      "triggers": [
        "cron"
      ],
      "reads": [
        "DB",
        "agent_outputs",
        "app_store_listings",
        "brand_threat_assessments",
        "brands",
        "campaigns",
        "ct_certificates",
        "dark_web_mentions",
        "email_security_scans",
        "geopolitical_campaign_links",
        "geopolitical_campaigns",
        "hosting_providers",
        "lookalike_domains",
        "notification_subscriptions",
        "social_mentions",
        "social_profiles",
        "spam_trap_captures",
        "threat_narratives",
        "threat_signals",
        "threats"
      ],
      "writes": [
        "agent_outputs"
      ],
      "ai_models_referenced": [],
      "loc": 1040,
      "last_modified": "2026-05-06T18:46:42.168Z"
    },
    {
      "name": "pathfinder",
      "path": "packages/trust-radar/src/agents/pathfinder.ts",
      "entrypoint": "pathfinderAgent",
      "triggers": [
        "manual"
      ],
      "reads": [
        "CACHE",
        "DB",
        "brand_threat_assessments",
        "brands",
        "email_security_scans",
        "org_brands",
        "phishing_pattern_signals",
        "sales_leads",
        "spam_trap_captures",
        "threat_signals",
        "threats"
      ],
      "writes": [],
      "ai_models_referenced": [],
      "loc": 692,
      "last_modified": "2026-05-04T17:56:39.962Z"
    },
    {
      "name": "public-trust-check",
      "path": "packages/trust-radar/src/agents/public-trust-check.ts",
      "entrypoint": "publicTrustCheckAgent",
      "triggers": [
        "http"
      ],
      "reads": [],
      "writes": [],
      "ai_models_referenced": [],
      "loc": 296,
      "last_modified": "2026-05-04T17:56:39.962Z"
    },
    {
      "name": "qualified-report",
      "path": "packages/trust-radar/src/agents/qualified-report.ts",
      "entrypoint": "qualifiedReportAgent",
      "triggers": [
        "http"
      ],
      "reads": [],
      "writes": [],
      "ai_models_referenced": [],
      "loc": 283,
      "last_modified": "2026-05-04T17:56:39.962Z"
    },
    {
      "name": "scan-report",
      "path": "packages/trust-radar/src/agents/scan-report.ts",
      "entrypoint": "scanReportAgent",
      "triggers": [
        "http"
      ],
      "reads": [],
      "writes": [],
      "ai_models_referenced": [],
      "loc": 218,
      "last_modified": "2026-05-04T17:56:39.962Z"
    },
    {
      "name": "seed-strategist",
      "path": "packages/trust-radar/src/agents/seed-strategist.ts",
      "entrypoint": "seedStrategistAgent",
      "triggers": [
        "cron"
      ],
      "reads": [
        "DB",
        "brands",
        "seed_campaigns",
        "spam_trap_captures"
      ],
      "writes": [
        "agent_outputs",
        "seed_addresses",
        "seed_campaigns"
      ],
      "ai_models_referenced": [],
      "loc": 231,
      "last_modified": "2026-05-04T17:56:39.962Z"
    },
    {
      "name": "sentinel",
      "path": "packages/trust-radar/src/agents/sentinel.ts",
      "entrypoint": "sentinelAgent",
      "triggers": [
        "queue"
      ],
      "reads": [
        "DB",
        "brands",
        "monitored_brands",
        "social_monitor_results",
        "social_profiles",
        "threat_actor_infrastructure",
        "threats"
      ],
      "writes": [
        "social_monitor_results",
        "threat_actor_infrastructure",
        "threat_actor_targets",
        "threat_actors",
        "threats"
      ],
      "ai_models_referenced": [],
      "loc": 601,
      "last_modified": "2026-05-07T14:55:22.364Z"
    },
    {
      "name": "social-ai-assessor",
      "path": "packages/trust-radar/src/agents/social-ai-assessor.ts",
      "entrypoint": "socialAiAssessorAgent",
      "triggers": [
        "http"
      ],
      "reads": [],
      "writes": [],
      "ai_models_referenced": [],
      "loc": 370,
      "last_modified": "2026-05-04T17:56:39.962Z"
    },
    {
      "name": "socialDiscovery",
      "path": "packages/trust-radar/src/agents/socialDiscovery.ts",
      "entrypoint": "socialDiscoveryAgent",
      "triggers": [
        "cron"
      ],
      "reads": [],
      "writes": [],
      "ai_models_referenced": [],
      "loc": 64,
      "last_modified": "2026-05-04T17:56:39.966Z"
    },
    {
      "name": "socialMonitor",
      "path": "packages/trust-radar/src/agents/socialMonitor.ts",
      "entrypoint": "socialMonitorAgent",
      "triggers": [
        "cron"
      ],
      "reads": [],
      "writes": [],
      "ai_models_referenced": [],
      "loc": 66,
      "last_modified": "2026-05-04T17:56:39.966Z"
    },
    {
      "name": "sparrow",
      "path": "packages/trust-radar/src/agents/sparrow.ts",
      "entrypoint": "sparrowAgent",
      "triggers": [
        "cron"
      ],
      "reads": [
        "DB",
        "app_store_listings",
        "brands",
        "dark_web_mentions",
        "social_mentions",
        "social_profiles",
        "takedown_evidence",
        "takedown_providers",
        "takedown_requests",
        "url_scan_results"
      ],
      "writes": [
        "takedown_evidence",
        "takedown_requests",
        "url_scan_results"
      ],
      "ai_models_referenced": [],
      "loc": 745,
      "last_modified": "2026-05-04T17:56:39.966Z"
    },
    {
      "name": "strategist",
      "path": "packages/trust-radar/src/agents/strategist.ts",
      "entrypoint": "strategistAgent",
      "triggers": [
        "cron"
      ],
      "reads": [
        "DB",
        "brands",
        "campaigns",
        "hosting_providers",
        "threats"
      ],
      "writes": [
        "agent_outputs",
        "campaigns",
        "threats"
      ],
      "ai_models_referenced": [],
      "loc": 569,
      "last_modified": "2026-05-04T17:56:39.966Z"
    },
    {
      "name": "trustbot",
      "path": "packages/trust-radar/src/agents/trustbot.ts",
      "entrypoint": "trustbotAgent",
      "triggers": [
        "manual"
      ],
      "reads": [
        "DB",
        "feed_schedules",
        "radar_agent_runs",
        "threats"
      ],
      "writes": [],
      "ai_models_referenced": [],
      "loc": 181,
      "last_modified": "2026-05-04T17:56:39.966Z"
    },
    {
      "name": "url-scan",
      "path": "packages/trust-radar/src/agents/url-scan.ts",
      "entrypoint": "urlScanAgent",
      "triggers": [
        "http"
      ],
      "reads": [],
      "writes": [],
      "ai_models_referenced": [],
      "loc": 228,
      "last_modified": "2026-05-04T17:56:39.966Z"
    },
    {
      "name": "watchdog",
      "path": "packages/trust-radar/src/agents/watchdog.ts",
      "entrypoint": "watchdogAgent",
      "triggers": [
        "queue"
      ],
      "reads": [
        "DB",
        "brands",
        "social_mentions"
      ],
      "writes": [
        "social_mentions",
        "threats"
      ],
      "ai_models_referenced": [],
      "loc": 362,
      "last_modified": "2026-05-04T17:56:39.966Z"
    }
  ],
  "feeds": [
    {
      "name": "abuseipdb",
      "path": "packages/trust-radar/src/feeds/abuseipdb.ts",
      "source_type": "http",
      "schedule": null,
      "loc": 242,
      "last_modified": "2026-05-04T17:56:39.982Z"
    },
    {
      "name": "blocklistde",
      "path": "packages/trust-radar/src/feeds/blocklistde.ts",
      "source_type": "http",
      "schedule": null,
      "loc": 98,
      "last_modified": "2026-05-04T17:56:39.982Z"
    },
    {
      "name": "c2intelfeeds",
      "path": "packages/trust-radar/src/feeds/c2intelfeeds.ts",
      "source_type": "http",
      "schedule": null,
      "loc": 169,
      "last_modified": "2026-05-04T17:56:39.982Z"
    },
    {
      "name": "c2tracker",
      "path": "packages/trust-radar/src/feeds/c2tracker.ts",
      "source_type": "unknown",
      "schedule": null,
      "loc": 33,
      "last_modified": "2026-05-04T17:56:39.982Z"
    },
    {
      "name": "certstream",
      "path": "packages/trust-radar/src/feeds/certstream.ts",
      "source_type": "http",
      "schedule": null,
      "loc": 237,
      "last_modified": "2026-05-04T17:56:39.982Z"
    },
    {
      "name": "cins_army",
      "path": "packages/trust-radar/src/feeds/cins_army.ts",
      "source_type": "unknown",
      "schedule": null,
      "loc": 103,
      "last_modified": "2026-05-04T17:56:39.982Z"
    },
    {
      "name": "circlPassiveDns",
      "path": "packages/trust-radar/src/feeds/circlPassiveDns.ts",
      "source_type": "http",
      "schedule": null,
      "loc": 192,
      "last_modified": "2026-05-04T17:56:39.982Z"
    },
    {
      "name": "cisa_iran_iocs",
      "path": "packages/trust-radar/src/feeds/cisa_iran_iocs.ts",
      "source_type": "unknown",
      "schedule": null,
      "loc": 194,
      "last_modified": "2026-05-04T17:56:39.982Z"
    },
    {
      "name": "cisa_kev",
      "path": "packages/trust-radar/src/feeds/cisa_kev.ts",
      "source_type": "unknown",
      "schedule": null,
      "loc": 93,
      "last_modified": "2026-05-04T17:56:39.982Z"
    },
    {
      "name": "cloudflare_email",
      "path": "packages/trust-radar/src/feeds/cloudflare_email.ts",
      "source_type": "api",
      "schedule": null,
      "loc": 134,
      "last_modified": "2026-05-04T17:56:39.986Z"
    },
    {
      "name": "cloudflare_scanner",
      "path": "packages/trust-radar/src/feeds/cloudflare_scanner.ts",
      "source_type": "api",
      "schedule": null,
      "loc": 286,
      "last_modified": "2026-05-04T17:56:39.986Z"
    },
    {
      "name": "disposableEmail",
      "path": "packages/trust-radar/src/feeds/disposableEmail.ts",
      "source_type": "http",
      "schedule": null,
      "loc": 97,
      "last_modified": "2026-05-04T17:56:39.986Z"
    },
    {
      "name": "dshield",
      "path": "packages/trust-radar/src/feeds/dshield.ts",
      "source_type": "http",
      "schedule": null,
      "loc": 64,
      "last_modified": "2026-05-04T17:56:39.986Z"
    },
    {
      "name": "emergingThreats",
      "path": "packages/trust-radar/src/feeds/emergingThreats.ts",
      "source_type": "http",
      "schedule": null,
      "loc": 90,
      "last_modified": "2026-05-04T17:56:39.986Z"
    },
    {
      "name": "feodo",
      "path": "packages/trust-radar/src/feeds/feodo.ts",
      "source_type": "http",
      "schedule": null,
      "loc": 101,
      "last_modified": "2026-05-04T17:56:39.986Z"
    },
    {
      "name": "github",
      "path": "packages/trust-radar/src/feeds/github.ts",
      "source_type": "api",
      "schedule": null,
      "loc": 438,
      "last_modified": "2026-05-06T18:46:42.172Z"
    },
    {
      "name": "googleSafeBrowsing",
      "path": "packages/trust-radar/src/feeds/googleSafeBrowsing.ts",
      "source_type": "http",
      "schedule": null,
      "loc": 271,
      "last_modified": "2026-05-04T17:56:39.986Z"
    },
    {
      "name": "greynoise",
      "path": "packages/trust-radar/src/feeds/greynoise.ts",
      "source_type": "http",
      "schedule": null,
      "loc": 264,
      "last_modified": "2026-05-04T17:56:39.986Z"
    },
    {
      "name": "hibp",
      "path": "packages/trust-radar/src/feeds/hibp.ts",
      "source_type": "http",
      "schedule": null,
      "loc": 161,
      "last_modified": "2026-05-04T17:56:39.986Z"
    },
    {
      "name": "itunes",
      "path": "packages/trust-radar/src/feeds/itunes.ts",
      "source_type": "http",
      "schedule": null,
      "loc": 153,
      "last_modified": "2026-05-04T17:56:39.986Z"
    },
    {
      "name": "malwarebazaar",
      "path": "packages/trust-radar/src/feeds/malwarebazaar.ts",
      "source_type": "unknown",
      "schedule": null,
      "loc": 99,
      "last_modified": "2026-05-04T17:56:39.986Z"
    },
    {
      "name": "mastodon",
      "path": "packages/trust-radar/src/feeds/mastodon.ts",
      "source_type": "http",
      "schedule": null,
      "loc": 350,
      "last_modified": "2026-05-06T18:46:42.172Z"
    },
    {
      "name": "nrd_hagezi",
      "path": "packages/trust-radar/src/feeds/nrd_hagezi.ts",
      "source_type": "http",
      "schedule": null,
      "loc": 247,
      "last_modified": "2026-05-04T17:56:39.986Z"
    },
    {
      "name": "openphish",
      "path": "packages/trust-radar/src/feeds/openphish.ts",
      "source_type": "http",
      "schedule": null,
      "loc": 44,
      "last_modified": "2026-05-04T17:56:39.990Z"
    },
    {
      "name": "otx_alienvault",
      "path": "packages/trust-radar/src/feeds/otx_alienvault.ts",
      "source_type": "unknown",
      "schedule": null,
      "loc": 162,
      "last_modified": "2026-05-06T18:46:42.172Z"
    },
    {
      "name": "phishdestroy",
      "path": "packages/trust-radar/src/feeds/phishdestroy.ts",
      "source_type": "http",
      "schedule": null,
      "loc": 138,
      "last_modified": "2026-05-06T18:46:42.172Z"
    },
    {
      "name": "phishtank",
      "path": "packages/trust-radar/src/feeds/phishtank.ts",
      "source_type": "http",
      "schedule": null,
      "loc": 73,
      "last_modified": "2026-05-04T17:56:39.990Z"
    },
    {
      "name": "psbdmp",
      "path": "packages/trust-radar/src/feeds/psbdmp.ts",
      "source_type": "http",
      "schedule": null,
      "loc": 179,
      "last_modified": "2026-05-04T17:56:39.990Z"
    },
    {
      "name": "reddit",
      "path": "packages/trust-radar/src/feeds/reddit.ts",
      "source_type": "api",
      "schedule": null,
      "loc": 353,
      "last_modified": "2026-05-04T17:56:39.990Z"
    },
    {
      "name": "seclookup",
      "path": "packages/trust-radar/src/feeds/seclookup.ts",
      "source_type": "api",
      "schedule": null,
      "loc": 270,
      "last_modified": "2026-05-04T17:56:39.990Z"
    },
    {
      "name": "spamhausDbl",
      "path": "packages/trust-radar/src/feeds/spamhausDbl.ts",
      "source_type": "http",
      "schedule": null,
      "loc": 254,
      "last_modified": "2026-05-04T17:56:39.990Z"
    },
    {
      "name": "spamhausDrop",
      "path": "packages/trust-radar/src/feeds/spamhausDrop.ts",
      "source_type": "http",
      "schedule": null,
      "loc": 144,
      "last_modified": "2026-05-04T17:56:39.990Z"
    },
    {
      "name": "sslbl",
      "path": "packages/trust-radar/src/feeds/sslbl.ts",
      "source_type": "http",
      "schedule": null,
      "loc": 99,
      "last_modified": "2026-05-04T17:56:39.990Z"
    },
    {
      "name": "surbl",
      "path": "packages/trust-radar/src/feeds/surbl.ts",
      "source_type": "http",
      "schedule": null,
      "loc": 205,
      "last_modified": "2026-05-04T17:56:39.990Z"
    },
    {
      "name": "telegram",
      "path": "packages/trust-radar/src/feeds/telegram.ts",
      "source_type": "http",
      "schedule": null,
      "loc": 415,
      "last_modified": "2026-05-04T17:56:39.990Z"
    },
    {
      "name": "threatfox",
      "path": "packages/trust-radar/src/feeds/threatfox.ts",
      "source_type": "unknown",
      "schedule": null,
      "loc": 111,
      "last_modified": "2026-05-06T18:46:42.172Z"
    },
    {
      "name": "torExitNodes",
      "path": "packages/trust-radar/src/feeds/torExitNodes.ts",
      "source_type": "http",
      "schedule": null,
      "loc": 88,
      "last_modified": "2026-05-04T17:56:39.990Z"
    },
    {
      "name": "typosquat_scanner",
      "path": "packages/trust-radar/src/feeds/typosquat_scanner.ts",
      "source_type": "http",
      "schedule": null,
      "loc": 219,
      "last_modified": "2026-05-04T17:56:39.994Z"
    },
    {
      "name": "urlhaus",
      "path": "packages/trust-radar/src/feeds/urlhaus.ts",
      "source_type": "unknown",
      "schedule": null,
      "loc": 82,
      "last_modified": "2026-05-04T17:56:39.994Z"
    },
    {
      "name": "virustotal",
      "path": "packages/trust-radar/src/feeds/virustotal.ts",
      "source_type": "api",
      "schedule": null,
      "loc": 211,
      "last_modified": "2026-05-04T17:56:39.994Z"
    }
  ],
  "crons": [
    {
      "pattern": "7 * * * *",
      "handler_path": "packages/trust-radar/src/index.ts",
      "agents_invoked": [
        "analyst",
        "appStoreMonitor",
        "attributor",
        "auto-seeder",
        "cartographer",
        "cube-healer",
        "darkWebMonitor",
        "flightControl",
        "geoip-refresh",
        "lookalike-scanner",
        "narrator",
        "news-watcher",
        "nexus",
        "notification_narrator",
        "observer",
        "seed-strategist",
        "socialDiscovery",
        "socialMonitor",
        "sparrow",
        "strategist"
      ]
    },
    {
      "pattern": "*/5 * * * *",
      "handler_path": "packages/trust-radar/src/index.ts",
      "agents_invoked": [
        "analyst",
        "appStoreMonitor",
        "attributor",
        "auto-seeder",
        "cartographer",
        "cube-healer",
        "darkWebMonitor",
        "flightControl",
        "geoip-refresh",
        "lookalike-scanner",
        "narrator",
        "news-watcher",
        "nexus",
        "notification_narrator",
        "observer",
        "seed-strategist",
        "socialDiscovery",
        "socialMonitor",
        "sparrow",
        "strategist"
      ]
    },
    {
      "pattern": "12 */6 * * *",
      "handler_path": "packages/trust-radar/src/index.ts",
      "agents_invoked": [
        "analyst",
        "appStoreMonitor",
        "attributor",
        "auto-seeder",
        "cartographer",
        "cube-healer",
        "darkWebMonitor",
        "flightControl",
        "geoip-refresh",
        "lookalike-scanner",
        "narrator",
        "news-watcher",
        "nexus",
        "notification_narrator",
        "observer",
        "seed-strategist",
        "socialDiscovery",
        "socialMonitor",
        "sparrow",
        "strategist"
      ]
    },
    {
      "pattern": "13 13 * * *",
      "handler_path": "packages/trust-radar/src/index.ts",
      "agents_invoked": [
        "analyst",
        "appStoreMonitor",
        "attributor",
        "auto-seeder",
        "cartographer",
        "cube-healer",
        "darkWebMonitor",
        "flightControl",
        "geoip-refresh",
        "lookalike-scanner",
        "narrator",
        "news-watcher",
        "nexus",
        "notification_narrator",
        "observer",
        "seed-strategist",
        "socialDiscovery",
        "socialMonitor",
        "sparrow",
        "strategist"
      ]
    }
  ],
  "workers": [
    {
      "name": "trust-radar",
      "path": "packages/trust-radar/src/index.ts",
      "bindings": [
        "ARCHITECT_BUNDLES",
        "AUDIT_DB",
        "CACHE",
        "CARTOGRAPHER_BACKFILL",
        "CERTSTREAM_MONITOR",
        "DB",
        "GEOIP_DB",
        "GEOIP_REFRESH",
        "GEOIP_STAGING",
        "NEXUS_RUN",
        "THREAT_PUSH_HUB"
      ]
    }
  ],
  "totals": {
    "agents": 38,
    "feeds": 40,
    "crons": 4,
    "workers": 1
  }
};
