/**
 * ARCHITECT repo manifest — GENERATED FILE. DO NOT EDIT BY HAND.
 *
 * Regenerated by scripts/build-architect-manifest.ts on every
 * averrow-worker build. Committed to git so the Worker has a
 * deterministic repo inventory at runtime without filesystem access.
 */

import type { RepoInventory } from "./types";

export const REPO_MANIFEST: RepoInventory = {
  "collected_at": "build-time",
  "agents": [
    {
      "name": "abuseMailboxClassifier",
      "path": "packages/averrow-worker/src/agents/abuseMailboxClassifier.ts",
      "entrypoint": "abuseMailboxClassifierAgent",
      "triggers": [
        "cron"
      ],
      "reads": [],
      "writes": [],
      "ai_models_referenced": [],
      "loc": 74,
      "last_modified": "2026-07-19T03:08:09.470Z"
    },
    {
      "name": "admin-classify",
      "path": "packages/averrow-worker/src/agents/admin-classify.ts",
      "entrypoint": "adminClassifyAgent",
      "triggers": [
        "http"
      ],
      "reads": [],
      "writes": [],
      "ai_models_referenced": [],
      "loc": 208,
      "last_modified": "2026-07-19T03:08:09.471Z"
    },
    {
      "name": "analyst",
      "path": "packages/averrow-worker/src/agents/analyst.ts",
      "entrypoint": "analystAgent",
      "triggers": [
        "cron"
      ],
      "reads": [
        "DB",
        "app_store_listings",
        "brand_threat_assessments",
        "brands",
        "dark_web_mentions",
        "geopolitical_campaign_links",
        "geopolitical_campaigns",
        "monitored_brands",
        "social_mentions",
        "social_profiles",
        "threats"
      ],
      "writes": [
        "agent_outputs",
        "brands",
        "threats"
      ],
      "ai_models_referenced": [],
      "loc": 1215,
      "last_modified": "2026-07-19T03:08:09.471Z"
    },
    {
      "name": "appStoreMonitor",
      "path": "packages/averrow-worker/src/agents/appStoreMonitor.ts",
      "entrypoint": "appStoreMonitorAgent",
      "triggers": [
        "cron"
      ],
      "reads": [],
      "writes": [],
      "ai_models_referenced": [],
      "loc": 63,
      "last_modified": "2026-07-19T03:08:09.471Z"
    },
    {
      "name": "attributor",
      "path": "packages/averrow-worker/src/agents/attributor.ts",
      "entrypoint": "attributorAgent",
      "triggers": [
        "cron"
      ],
      "reads": [
        "DB",
        "infrastructure_clusters",
        "threat_actors",
        "threats"
      ],
      "writes": [
        "infrastructure_clusters"
      ],
      "ai_models_referenced": [],
      "loc": 387,
      "last_modified": "2026-07-19T03:08:09.475Z"
    },
    {
      "name": "auto-seeder",
      "path": "packages/averrow-worker/src/agents/auto-seeder.ts",
      "entrypoint": "autoSeederAgent",
      "triggers": [
        "cron"
      ],
      "reads": [
        "DB",
        "seed_domains"
      ],
      "writes": [],
      "ai_models_referenced": [],
      "loc": 141,
      "last_modified": "2026-07-19T03:08:09.475Z"
    },
    {
      "name": "brand-analysis",
      "path": "packages/averrow-worker/src/agents/brand-analysis.ts",
      "entrypoint": "brandAnalysisAgent",
      "triggers": [
        "http"
      ],
      "reads": [],
      "writes": [],
      "ai_models_referenced": [],
      "loc": 247,
      "last_modified": "2026-07-19T03:08:09.475Z"
    },
    {
      "name": "brand-deep-scan",
      "path": "packages/averrow-worker/src/agents/brand-deep-scan.ts",
      "entrypoint": "brandDeepScanAgent",
      "triggers": [
        "http"
      ],
      "reads": [],
      "writes": [],
      "ai_models_referenced": [],
      "loc": 246,
      "last_modified": "2026-07-19T03:08:09.475Z"
    },
    {
      "name": "brand-enricher",
      "path": "packages/averrow-worker/src/agents/brand-enricher.ts",
      "entrypoint": "brandEnricherAgent",
      "triggers": [
        "http"
      ],
      "reads": [],
      "writes": [],
      "ai_models_referenced": [],
      "loc": 143,
      "last_modified": "2026-07-19T03:08:09.475Z"
    },
    {
      "name": "brand-report",
      "path": "packages/averrow-worker/src/agents/brand-report.ts",
      "entrypoint": "brandReportAgent",
      "triggers": [
        "http"
      ],
      "reads": [],
      "writes": [],
      "ai_models_referenced": [],
      "loc": 245,
      "last_modified": "2026-07-19T03:08:09.475Z"
    },
    {
      "name": "campaign-hunter",
      "path": "packages/averrow-worker/src/agents/campaign-hunter.ts",
      "entrypoint": "campaignHunterAgent",
      "triggers": [
        "http"
      ],
      "reads": [
        "DB",
        "brands"
      ],
      "writes": [],
      "ai_models_referenced": [],
      "loc": 284,
      "last_modified": "2026-07-19T03:08:09.475Z"
    },
    {
      "name": "cartographer",
      "path": "packages/averrow-worker/src/agents/cartographer.ts",
      "entrypoint": "cartographerAgent",
      "triggers": [
        "cron",
        "queue"
      ],
      "reads": [
        "CACHE",
        "DB",
        "brands",
        "dmarc_report_records",
        "geopolitical_campaign_links",
        "geopolitical_campaigns",
        "hosting_providers",
        "threat_cube_provider",
        "threats"
      ],
      "writes": [
        "agent_events",
        "alerts",
        "brands",
        "dmarc_report_records",
        "hosting_providers",
        "merges",
        "provider_threat_stats",
        "threats"
      ],
      "ai_models_referenced": [],
      "loc": 1356,
      "last_modified": "2026-07-19T03:08:09.475Z"
    },
    {
      "name": "ct-monitor",
      "path": "packages/averrow-worker/src/agents/ct-monitor.ts",
      "entrypoint": "ctMonitorAgent",
      "triggers": [
        "cron"
      ],
      "reads": [],
      "writes": [],
      "ai_models_referenced": [],
      "loc": 71,
      "last_modified": "2026-07-19T03:08:09.475Z"
    },
    {
      "name": "cube-healer",
      "path": "packages/averrow-worker/src/agents/cube-healer.ts",
      "entrypoint": "cubeHealerAgent",
      "triggers": [
        "cron"
      ],
      "reads": [
        "CACHE",
        "DB",
        "threats"
      ],
      "writes": [
        "threat_cube_arcs",
        "threat_cube_brand",
        "threat_cube_geo",
        "threat_cube_provider",
        "threat_cube_status"
      ],
      "ai_models_referenced": [],
      "loc": 492,
      "last_modified": "2026-07-19T03:08:09.475Z"
    },
    {
      "name": "curator",
      "path": "packages/averrow-worker/src/agents/curator.ts",
      "entrypoint": "curatorAgent",
      "triggers": [
        "queue"
      ],
      "reads": [
        "DB",
        "brands",
        "social_profiles"
      ],
      "writes": [
        "brands",
        "social_profiles",
        "threats"
      ],
      "ai_models_referenced": [],
      "loc": 231,
      "last_modified": "2026-07-19T03:08:09.475Z"
    },
    {
      "name": "darkWebMonitor",
      "path": "packages/averrow-worker/src/agents/darkWebMonitor.ts",
      "entrypoint": "darkWebMonitorAgent",
      "triggers": [
        "cron"
      ],
      "reads": [],
      "writes": [],
      "ai_models_referenced": [],
      "loc": 71,
      "last_modified": "2026-07-19T03:08:09.475Z"
    },
    {
      "name": "evidence-assembler",
      "path": "packages/averrow-worker/src/agents/evidence-assembler.ts",
      "entrypoint": "evidenceAssemblerAgent",
      "triggers": [
        "http"
      ],
      "reads": [],
      "writes": [],
      "ai_models_referenced": [],
      "loc": 304,
      "last_modified": "2026-07-19T03:08:09.475Z"
    },
    {
      "name": "executiveMonitor",
      "path": "packages/averrow-worker/src/agents/executiveMonitor.ts",
      "entrypoint": "executiveMonitorAgent",
      "triggers": [
        "cron"
      ],
      "reads": [],
      "writes": [],
      "ai_models_referenced": [],
      "loc": 82,
      "last_modified": "2026-07-20T17:37:28.688Z"
    },
    {
      "name": "flightControl",
      "path": "packages/averrow-worker/src/agents/flightControl.ts",
      "entrypoint": "flightControlAgent",
      "triggers": [
        "cron"
      ],
      "reads": [
        "CACHE",
        "CERTSTREAM_MONITOR",
        "DB",
        "abuse_inbox_messages",
        "agent_configs",
        "agent_outputs",
        "agent_runs",
        "backlog_history",
        "brands",
        "budget_ledger",
        "daily_snapshots",
        "dns_queue",
        "feed_configs",
        "feed_pull_history",
        "feed_status",
        "geo_ip_refresh_log",
        "hosting_providers",
        "incidents",
        "push_subscriptions",
        "seed_addresses",
        "social_mentions",
        "spam_trap_captures",
        "threat_briefings",
        "threats"
      ],
      "writes": [
        "agent_activity_log",
        "agent_runs",
        "backlog_history",
        "geo_ip_refresh_log",
        "incident_updates",
        "push_subscriptions"
      ],
      "ai_models_referenced": [],
      "loc": 2626,
      "last_modified": "2026-07-19T03:08:09.477Z"
    },
    {
      "name": "geo-campaign-assessment",
      "path": "packages/averrow-worker/src/agents/geo-campaign-assessment.ts",
      "entrypoint": "geoCampaignAssessmentAgent",
      "triggers": [
        "http"
      ],
      "reads": [],
      "writes": [],
      "ai_models_referenced": [],
      "loc": 254,
      "last_modified": "2026-07-19T03:08:09.477Z"
    },
    {
      "name": "geoip-refresh",
      "path": "packages/averrow-worker/src/agents/geoip-refresh.ts",
      "entrypoint": "geoipRefreshAgent",
      "triggers": [
        "cron"
      ],
      "reads": [
        "CACHE",
        "geo_ip_refresh_log"
      ],
      "writes": [
        "geo_ip_refresh_log"
      ],
      "ai_models_referenced": [],
      "loc": 638,
      "last_modified": "2026-07-19T03:08:09.477Z"
    },
    {
      "name": "honeypot-generator",
      "path": "packages/averrow-worker/src/agents/honeypot-generator.ts",
      "entrypoint": "honeypotGeneratorAgent",
      "triggers": [
        "http"
      ],
      "reads": [],
      "writes": [],
      "ai_models_referenced": [],
      "loc": 206,
      "last_modified": "2026-07-19T03:08:09.477Z"
    },
    {
      "name": "lookalike-scanner",
      "path": "packages/averrow-worker/src/agents/lookalike-scanner.ts",
      "entrypoint": "lookalikeScannerAgent",
      "triggers": [
        "cron"
      ],
      "reads": [],
      "writes": [],
      "ai_models_referenced": [],
      "loc": 120,
      "last_modified": "2026-07-20T13:21:54.463Z"
    },
    {
      "name": "narrator",
      "path": "packages/averrow-worker/src/agents/narrator.ts",
      "entrypoint": "narratorAgent",
      "triggers": [
        "cron"
      ],
      "reads": [
        "DB",
        "app_store_listings",
        "brands",
        "ct_certificates",
        "dark_web_mentions",
        "lookalike_domains",
        "social_monitor_results",
        "threat_narratives",
        "threats"
      ],
      "writes": [
        "threat_narratives"
      ],
      "ai_models_referenced": [],
      "loc": 505,
      "last_modified": "2026-07-19T03:08:09.477Z"
    },
    {
      "name": "news-watcher",
      "path": "packages/averrow-worker/src/agents/news-watcher.ts",
      "entrypoint": "newsWatcherAgent",
      "triggers": [
        "cron"
      ],
      "reads": [
        "DB",
        "geopolitical_campaigns",
        "news_articles"
      ],
      "writes": [
        "geopolitical_campaigns",
        "news_articles"
      ],
      "ai_models_referenced": [],
      "loc": 323,
      "last_modified": "2026-07-19T03:08:09.477Z"
    },
    {
      "name": "nexus",
      "path": "packages/averrow-worker/src/agents/nexus.ts",
      "entrypoint": "nexusAgent",
      "triggers": [
        "cron",
        "queue"
      ],
      "reads": [
        "DB",
        "app_store_listings",
        "brands",
        "dark_web_mentions",
        "threats"
      ],
      "writes": [
        "agent_events",
        "agent_runs",
        "infrastructure_clusters",
        "threats"
      ],
      "ai_models_referenced": [],
      "loc": 1342,
      "last_modified": "2026-07-20T03:50:40.959Z"
    },
    {
      "name": "notification_narrator",
      "path": "packages/averrow-worker/src/agents/notification_narrator.ts",
      "entrypoint": "notificationNarratorAgent",
      "triggers": [
        "cron"
      ],
      "reads": [
        "DB",
        "notification_preferences_v2",
        "notifications",
        "users"
      ],
      "writes": [],
      "ai_models_referenced": [],
      "loc": 187,
      "last_modified": "2026-07-19T03:08:09.477Z"
    },
    {
      "name": "observer",
      "path": "packages/averrow-worker/src/agents/observer.ts",
      "entrypoint": "observerAgent",
      "triggers": [
        "cron"
      ],
      "reads": [
        "DB",
        "agent_outputs",
        "app_store_listings",
        "brand_threat_assessments",
        "brands",
        "campaigns",
        "ct_certificates",
        "dark_web_mentions",
        "email_security_scans",
        "geopolitical_campaign_links",
        "geopolitical_campaigns",
        "hosting_providers",
        "lookalike_domains",
        "notification_subscriptions",
        "social_mentions",
        "social_profiles",
        "spam_trap_captures",
        "threat_narratives",
        "threat_signals",
        "threats"
      ],
      "writes": [
        "agent_outputs"
      ],
      "ai_models_referenced": [],
      "loc": 1043,
      "last_modified": "2026-07-19T03:08:09.481Z"
    },
    {
      "name": "pathfinder",
      "path": "packages/averrow-worker/src/agents/pathfinder.ts",
      "entrypoint": "pathfinderAgent",
      "triggers": [
        "manual"
      ],
      "reads": [
        "CACHE",
        "DB",
        "brand_firmographics",
        "brand_threat_assessments",
        "brands",
        "email_security_scans",
        "org_brands",
        "phishing_pattern_signals",
        "sales_leads",
        "spam_trap_captures",
        "threat_signals",
        "threats"
      ],
      "writes": [],
      "ai_models_referenced": [],
      "loc": 831,
      "last_modified": "2026-07-19T03:08:09.481Z"
    },
    {
      "name": "public-trust-check",
      "path": "packages/averrow-worker/src/agents/public-trust-check.ts",
      "entrypoint": "publicTrustCheckAgent",
      "triggers": [
        "http"
      ],
      "reads": [],
      "writes": [],
      "ai_models_referenced": [],
      "loc": 296,
      "last_modified": "2026-07-19T03:08:09.481Z"
    },
    {
      "name": "qualified-report",
      "path": "packages/averrow-worker/src/agents/qualified-report.ts",
      "entrypoint": "qualifiedReportAgent",
      "triggers": [
        "http"
      ],
      "reads": [],
      "writes": [],
      "ai_models_referenced": [],
      "loc": 283,
      "last_modified": "2026-07-19T03:08:09.481Z"
    },
    {
      "name": "scan-report",
      "path": "packages/averrow-worker/src/agents/scan-report.ts",
      "entrypoint": "scanReportAgent",
      "triggers": [
        "http"
      ],
      "reads": [],
      "writes": [],
      "ai_models_referenced": [],
      "loc": 218,
      "last_modified": "2026-07-19T03:08:09.481Z"
    },
    {
      "name": "seed-strategist",
      "path": "packages/averrow-worker/src/agents/seed-strategist.ts",
      "entrypoint": "seedStrategistAgent",
      "triggers": [
        "cron"
      ],
      "reads": [
        "DB",
        "brands",
        "seed_campaigns",
        "spam_trap_captures"
      ],
      "writes": [
        "agent_outputs",
        "seed_addresses",
        "seed_campaigns"
      ],
      "ai_models_referenced": [],
      "loc": 260,
      "last_modified": "2026-07-19T03:08:09.481Z"
    },
    {
      "name": "sentinel",
      "path": "packages/averrow-worker/src/agents/sentinel.ts",
      "entrypoint": "sentinelAgent",
      "triggers": [
        "queue"
      ],
      "reads": [
        "DB",
        "brands",
        "monitored_brands",
        "social_monitor_results",
        "social_profiles",
        "threat_actor_infrastructure",
        "threats"
      ],
      "writes": [
        "social_monitor_results",
        "threat_actor_infrastructure",
        "threat_actor_targets",
        "threat_actors",
        "threats"
      ],
      "ai_models_referenced": [],
      "loc": 755,
      "last_modified": "2026-07-19T03:08:09.481Z"
    },
    {
      "name": "social-ai-assessor",
      "path": "packages/averrow-worker/src/agents/social-ai-assessor.ts",
      "entrypoint": "socialAiAssessorAgent",
      "triggers": [
        "http"
      ],
      "reads": [],
      "writes": [],
      "ai_models_referenced": [],
      "loc": 370,
      "last_modified": "2026-07-19T03:08:09.481Z"
    },
    {
      "name": "socialDiscovery",
      "path": "packages/averrow-worker/src/agents/socialDiscovery.ts",
      "entrypoint": "socialDiscoveryAgent",
      "triggers": [
        "cron"
      ],
      "reads": [],
      "writes": [],
      "ai_models_referenced": [],
      "loc": 64,
      "last_modified": "2026-07-19T03:08:09.481Z"
    },
    {
      "name": "socialMonitor",
      "path": "packages/averrow-worker/src/agents/socialMonitor.ts",
      "entrypoint": "socialMonitorAgent",
      "triggers": [
        "cron"
      ],
      "reads": [],
      "writes": [],
      "ai_models_referenced": [],
      "loc": 66,
      "last_modified": "2026-07-19T03:08:09.481Z"
    },
    {
      "name": "sparrow",
      "path": "packages/averrow-worker/src/agents/sparrow.ts",
      "entrypoint": "sparrowAgent",
      "triggers": [
        "cron"
      ],
      "reads": [
        "DB",
        "abuse_inbox_messages",
        "app_store_listings",
        "brands",
        "dark_web_mentions",
        "lookalike_domains",
        "org_brands",
        "social_mentions",
        "social_profiles",
        "takedown_authorizations",
        "takedown_evidence",
        "takedown_providers",
        "takedown_requests",
        "takedown_submissions",
        "threats",
        "url_scan_results"
      ],
      "writes": [
        "abuse_inbox_messages",
        "lookalike_domains",
        "takedown_evidence",
        "takedown_requests",
        "url_scan_results"
      ],
      "ai_models_referenced": [],
      "loc": 1477,
      "last_modified": "2026-07-19T03:08:09.481Z"
    },
    {
      "name": "strategist",
      "path": "packages/averrow-worker/src/agents/strategist.ts",
      "entrypoint": "strategistAgent",
      "triggers": [
        "cron"
      ],
      "reads": [
        "DB",
        "brands",
        "campaigns",
        "hosting_providers",
        "threats"
      ],
      "writes": [
        "agent_outputs",
        "campaigns",
        "threats"
      ],
      "ai_models_referenced": [],
      "loc": 683,
      "last_modified": "2026-07-19T03:08:09.481Z"
    },
    {
      "name": "trademarkMonitor",
      "path": "packages/averrow-worker/src/agents/trademarkMonitor.ts",
      "entrypoint": "trademarkMonitorAgent",
      "triggers": [
        "cron"
      ],
      "reads": [],
      "writes": [],
      "ai_models_referenced": [],
      "loc": 56,
      "last_modified": "2026-07-19T03:08:09.485Z"
    },
    {
      "name": "trustbot",
      "path": "packages/averrow-worker/src/agents/trustbot.ts",
      "entrypoint": "trustbotAgent",
      "triggers": [
        "manual"
      ],
      "reads": [
        "DB",
        "feed_schedules",
        "radar_agent_runs",
        "threats"
      ],
      "writes": [],
      "ai_models_referenced": [],
      "loc": 181,
      "last_modified": "2026-07-19T03:08:09.485Z"
    },
    {
      "name": "url-scan",
      "path": "packages/averrow-worker/src/agents/url-scan.ts",
      "entrypoint": "urlScanAgent",
      "triggers": [
        "http"
      ],
      "reads": [],
      "writes": [],
      "ai_models_referenced": [],
      "loc": 228,
      "last_modified": "2026-07-19T03:08:09.485Z"
    },
    {
      "name": "watchdog",
      "path": "packages/averrow-worker/src/agents/watchdog.ts",
      "entrypoint": "watchdogAgent",
      "triggers": [
        "queue"
      ],
      "reads": [
        "DB",
        "brands",
        "social_mentions"
      ],
      "writes": [
        "social_mentions",
        "threats"
      ],
      "ai_models_referenced": [],
      "loc": 362,
      "last_modified": "2026-07-19T03:08:09.485Z"
    }
  ],
  "feeds": [
    {
      "name": "abuseipdb",
      "path": "packages/averrow-worker/src/feeds/abuseipdb.ts",
      "source_type": "http",
      "schedule": null,
      "loc": 265,
      "last_modified": "2026-07-19T03:08:09.494Z"
    },
    {
      "name": "advisories",
      "path": "packages/averrow-worker/src/feeds/advisories.ts",
      "source_type": "rss",
      "schedule": null,
      "loc": 326,
      "last_modified": "2026-07-19T03:08:09.494Z"
    },
    {
      "name": "blocklistde",
      "path": "packages/averrow-worker/src/feeds/blocklistde.ts",
      "source_type": "http",
      "schedule": null,
      "loc": 98,
      "last_modified": "2026-07-19T03:08:09.494Z"
    },
    {
      "name": "c2intelfeeds",
      "path": "packages/averrow-worker/src/feeds/c2intelfeeds.ts",
      "source_type": "http",
      "schedule": null,
      "loc": 169,
      "last_modified": "2026-07-19T03:08:09.494Z"
    },
    {
      "name": "c2tracker",
      "path": "packages/averrow-worker/src/feeds/c2tracker.ts",
      "source_type": "unknown",
      "schedule": null,
      "loc": 33,
      "last_modified": "2026-07-19T03:08:09.494Z"
    },
    {
      "name": "certstream",
      "path": "packages/averrow-worker/src/feeds/certstream.ts",
      "source_type": "stream",
      "schedule": null,
      "loc": 273,
      "last_modified": "2026-07-19T03:08:09.494Z"
    },
    {
      "name": "cins_army",
      "path": "packages/averrow-worker/src/feeds/cins_army.ts",
      "source_type": "unknown",
      "schedule": null,
      "loc": 103,
      "last_modified": "2026-07-19T03:08:09.494Z"
    },
    {
      "name": "circlPassiveDns",
      "path": "packages/averrow-worker/src/feeds/circlPassiveDns.ts",
      "source_type": "http",
      "schedule": null,
      "loc": 192,
      "last_modified": "2026-07-19T03:08:09.494Z"
    },
    {
      "name": "cisa_iran_iocs",
      "path": "packages/averrow-worker/src/feeds/cisa_iran_iocs.ts",
      "source_type": "unknown",
      "schedule": null,
      "loc": 194,
      "last_modified": "2026-07-19T03:08:09.494Z"
    },
    {
      "name": "cisa_kev",
      "path": "packages/averrow-worker/src/feeds/cisa_kev.ts",
      "source_type": "unknown",
      "schedule": null,
      "loc": 93,
      "last_modified": "2026-07-19T03:08:09.494Z"
    },
    {
      "name": "cloudflare_email",
      "path": "packages/averrow-worker/src/feeds/cloudflare_email.ts",
      "source_type": "api",
      "schedule": null,
      "loc": 134,
      "last_modified": "2026-07-19T03:08:09.494Z"
    },
    {
      "name": "cloudflare_scanner",
      "path": "packages/averrow-worker/src/feeds/cloudflare_scanner.ts",
      "source_type": "api",
      "schedule": null,
      "loc": 286,
      "last_modified": "2026-07-19T03:08:09.494Z"
    },
    {
      "name": "cryptoscamdb",
      "path": "packages/averrow-worker/src/feeds/cryptoscamdb.ts",
      "source_type": "http",
      "schedule": null,
      "loc": 140,
      "last_modified": "2026-07-19T03:08:09.494Z"
    },
    {
      "name": "dataplane",
      "path": "packages/averrow-worker/src/feeds/dataplane.ts",
      "source_type": "http",
      "schedule": null,
      "loc": 228,
      "last_modified": "2026-07-19T03:08:09.497Z"
    },
    {
      "name": "digitalside_osint",
      "path": "packages/averrow-worker/src/feeds/digitalside_osint.ts",
      "source_type": "http",
      "schedule": null,
      "loc": 164,
      "last_modified": "2026-07-19T03:08:09.497Z"
    },
    {
      "name": "disposableEmail",
      "path": "packages/averrow-worker/src/feeds/disposableEmail.ts",
      "source_type": "http",
      "schedule": null,
      "loc": 103,
      "last_modified": "2026-07-19T03:08:09.497Z"
    },
    {
      "name": "dshield",
      "path": "packages/averrow-worker/src/feeds/dshield.ts",
      "source_type": "http",
      "schedule": null,
      "loc": 64,
      "last_modified": "2026-07-19T03:08:09.497Z"
    },
    {
      "name": "emergingThreats",
      "path": "packages/averrow-worker/src/feeds/emergingThreats.ts",
      "source_type": "http",
      "schedule": null,
      "loc": 90,
      "last_modified": "2026-07-19T03:08:09.497Z"
    },
    {
      "name": "feodo",
      "path": "packages/averrow-worker/src/feeds/feodo.ts",
      "source_type": "http",
      "schedule": null,
      "loc": 101,
      "last_modified": "2026-07-19T03:08:09.497Z"
    },
    {
      "name": "github",
      "path": "packages/averrow-worker/src/feeds/github.ts",
      "source_type": "api",
      "schedule": null,
      "loc": 438,
      "last_modified": "2026-07-19T03:08:09.497Z"
    },
    {
      "name": "googleSafeBrowsing",
      "path": "packages/averrow-worker/src/feeds/googleSafeBrowsing.ts",
      "source_type": "http",
      "schedule": null,
      "loc": 271,
      "last_modified": "2026-07-19T03:08:09.497Z"
    },
    {
      "name": "greynoise",
      "path": "packages/averrow-worker/src/feeds/greynoise.ts",
      "source_type": "http",
      "schedule": null,
      "loc": 277,
      "last_modified": "2026-07-19T03:08:09.497Z"
    },
    {
      "name": "hibp",
      "path": "packages/averrow-worker/src/feeds/hibp.ts",
      "source_type": "http",
      "schedule": null,
      "loc": 161,
      "last_modified": "2026-07-19T03:08:09.497Z"
    },
    {
      "name": "itunes",
      "path": "packages/averrow-worker/src/feeds/itunes.ts",
      "source_type": "http",
      "schedule": null,
      "loc": 153,
      "last_modified": "2026-07-19T03:08:09.497Z"
    },
    {
      "name": "malwarebazaar",
      "path": "packages/averrow-worker/src/feeds/malwarebazaar.ts",
      "source_type": "unknown",
      "schedule": null,
      "loc": 99,
      "last_modified": "2026-07-19T03:08:09.497Z"
    },
    {
      "name": "mastodon",
      "path": "packages/averrow-worker/src/feeds/mastodon.ts",
      "source_type": "http",
      "schedule": null,
      "loc": 350,
      "last_modified": "2026-07-19T03:08:09.497Z"
    },
    {
      "name": "nrd_hagezi",
      "path": "packages/averrow-worker/src/feeds/nrd_hagezi.ts",
      "source_type": "http",
      "schedule": null,
      "loc": 247,
      "last_modified": "2026-07-19T03:08:09.497Z"
    },
    {
      "name": "nvd_cve",
      "path": "packages/averrow-worker/src/feeds/nvd_cve.ts",
      "source_type": "unknown",
      "schedule": null,
      "loc": 266,
      "last_modified": "2026-07-19T03:08:09.497Z"
    },
    {
      "name": "openphish",
      "path": "packages/averrow-worker/src/feeds/openphish.ts",
      "source_type": "http",
      "schedule": null,
      "loc": 44,
      "last_modified": "2026-07-19T03:08:09.497Z"
    },
    {
      "name": "otx_alienvault",
      "path": "packages/averrow-worker/src/feeds/otx_alienvault.ts",
      "source_type": "unknown",
      "schedule": null,
      "loc": 162,
      "last_modified": "2026-07-19T03:08:09.501Z"
    },
    {
      "name": "phishdestroy",
      "path": "packages/averrow-worker/src/feeds/phishdestroy.ts",
      "source_type": "http",
      "schedule": null,
      "loc": 138,
      "last_modified": "2026-07-19T03:08:09.501Z"
    },
    {
      "name": "phishstats",
      "path": "packages/averrow-worker/src/feeds/phishstats.ts",
      "source_type": "http",
      "schedule": null,
      "loc": 102,
      "last_modified": "2026-07-19T03:08:09.501Z"
    },
    {
      "name": "phishtank",
      "path": "packages/averrow-worker/src/feeds/phishtank.ts",
      "source_type": "http",
      "schedule": null,
      "loc": 73,
      "last_modified": "2026-07-19T03:08:09.501Z"
    },
    {
      "name": "psbdmp",
      "path": "packages/averrow-worker/src/feeds/psbdmp.ts",
      "source_type": "http",
      "schedule": null,
      "loc": 180,
      "last_modified": "2026-07-19T03:08:09.501Z"
    },
    {
      "name": "reddit",
      "path": "packages/averrow-worker/src/feeds/reddit.ts",
      "source_type": "api",
      "schedule": null,
      "loc": 353,
      "last_modified": "2026-07-19T03:08:09.501Z"
    },
    {
      "name": "seclookup",
      "path": "packages/averrow-worker/src/feeds/seclookup.ts",
      "source_type": "api",
      "schedule": null,
      "loc": 283,
      "last_modified": "2026-07-19T03:08:09.501Z"
    },
    {
      "name": "spamhausDbl",
      "path": "packages/averrow-worker/src/feeds/spamhausDbl.ts",
      "source_type": "http",
      "schedule": null,
      "loc": 254,
      "last_modified": "2026-07-19T03:08:09.501Z"
    },
    {
      "name": "spamhausDrop",
      "path": "packages/averrow-worker/src/feeds/spamhausDrop.ts",
      "source_type": "http",
      "schedule": null,
      "loc": 171,
      "last_modified": "2026-07-19T03:08:09.501Z"
    },
    {
      "name": "sslbl",
      "path": "packages/averrow-worker/src/feeds/sslbl.ts",
      "source_type": "http",
      "schedule": null,
      "loc": 99,
      "last_modified": "2026-07-19T03:08:09.501Z"
    },
    {
      "name": "surbl",
      "path": "packages/averrow-worker/src/feeds/surbl.ts",
      "source_type": "http",
      "schedule": null,
      "loc": 210,
      "last_modified": "2026-07-19T03:08:09.501Z"
    },
    {
      "name": "talos_ips",
      "path": "packages/averrow-worker/src/feeds/talos_ips.ts",
      "source_type": "http",
      "schedule": null,
      "loc": 77,
      "last_modified": "2026-07-19T03:08:09.501Z"
    },
    {
      "name": "taxii",
      "path": "packages/averrow-worker/src/feeds/taxii.ts",
      "source_type": "api",
      "schedule": null,
      "loc": 318,
      "last_modified": "2026-07-19T03:08:09.501Z"
    },
    {
      "name": "telegram",
      "path": "packages/averrow-worker/src/feeds/telegram.ts",
      "source_type": "http",
      "schedule": null,
      "loc": 492,
      "last_modified": "2026-07-19T03:08:09.501Z"
    },
    {
      "name": "threatfox",
      "path": "packages/averrow-worker/src/feeds/threatfox.ts",
      "source_type": "unknown",
      "schedule": null,
      "loc": 111,
      "last_modified": "2026-07-19T03:08:09.501Z"
    },
    {
      "name": "torExitNodes",
      "path": "packages/averrow-worker/src/feeds/torExitNodes.ts",
      "source_type": "http",
      "schedule": null,
      "loc": 88,
      "last_modified": "2026-07-19T03:08:09.501Z"
    },
    {
      "name": "tweetfeed",
      "path": "packages/averrow-worker/src/feeds/tweetfeed.ts",
      "source_type": "http",
      "schedule": null,
      "loc": 156,
      "last_modified": "2026-07-19T03:08:09.501Z"
    },
    {
      "name": "typosquat_scanner",
      "path": "packages/averrow-worker/src/feeds/typosquat_scanner.ts",
      "source_type": "http",
      "schedule": null,
      "loc": 219,
      "last_modified": "2026-07-19T03:08:09.505Z"
    },
    {
      "name": "urlhaus",
      "path": "packages/averrow-worker/src/feeds/urlhaus.ts",
      "source_type": "unknown",
      "schedule": null,
      "loc": 82,
      "last_modified": "2026-07-19T03:08:09.505Z"
    },
    {
      "name": "urlscanio",
      "path": "packages/averrow-worker/src/feeds/urlscanio.ts",
      "source_type": "api",
      "schedule": null,
      "loc": 167,
      "last_modified": "2026-07-19T03:08:09.505Z"
    },
    {
      "name": "virustotal",
      "path": "packages/averrow-worker/src/feeds/virustotal.ts",
      "source_type": "api",
      "schedule": null,
      "loc": 252,
      "last_modified": "2026-07-19T16:34:39.776Z"
    }
  ],
  "crons": [
    {
      "pattern": "7 * * * *",
      "handler_path": "packages/averrow-worker/src/index.ts",
      "agents_invoked": [
        "abuseMailboxClassifier",
        "analyst",
        "appStoreMonitor",
        "attributor",
        "auto-seeder",
        "cartographer",
        "ct-monitor",
        "cube-healer",
        "darkWebMonitor",
        "executiveMonitor",
        "flightControl",
        "geoip-refresh",
        "lookalike-scanner",
        "narrator",
        "news-watcher",
        "nexus",
        "notification_narrator",
        "observer",
        "seed-strategist",
        "socialDiscovery",
        "socialMonitor",
        "sparrow",
        "strategist",
        "trademarkMonitor"
      ]
    },
    {
      "pattern": "8 * * * *",
      "handler_path": "packages/averrow-worker/src/index.ts",
      "agents_invoked": [
        "abuseMailboxClassifier",
        "analyst",
        "appStoreMonitor",
        "attributor",
        "auto-seeder",
        "cartographer",
        "ct-monitor",
        "cube-healer",
        "darkWebMonitor",
        "executiveMonitor",
        "flightControl",
        "geoip-refresh",
        "lookalike-scanner",
        "narrator",
        "news-watcher",
        "nexus",
        "notification_narrator",
        "observer",
        "seed-strategist",
        "socialDiscovery",
        "socialMonitor",
        "sparrow",
        "strategist",
        "trademarkMonitor"
      ]
    },
    {
      "pattern": "9 * * * *",
      "handler_path": "packages/averrow-worker/src/index.ts",
      "agents_invoked": [
        "abuseMailboxClassifier",
        "analyst",
        "appStoreMonitor",
        "attributor",
        "auto-seeder",
        "cartographer",
        "ct-monitor",
        "cube-healer",
        "darkWebMonitor",
        "executiveMonitor",
        "flightControl",
        "geoip-refresh",
        "lookalike-scanner",
        "narrator",
        "news-watcher",
        "nexus",
        "notification_narrator",
        "observer",
        "seed-strategist",
        "socialDiscovery",
        "socialMonitor",
        "sparrow",
        "strategist",
        "trademarkMonitor"
      ]
    },
    {
      "pattern": "10 */6 * * *",
      "handler_path": "packages/averrow-worker/src/index.ts",
      "agents_invoked": [
        "abuseMailboxClassifier",
        "analyst",
        "appStoreMonitor",
        "attributor",
        "auto-seeder",
        "cartographer",
        "ct-monitor",
        "cube-healer",
        "darkWebMonitor",
        "executiveMonitor",
        "flightControl",
        "geoip-refresh",
        "lookalike-scanner",
        "narrator",
        "news-watcher",
        "nexus",
        "notification_narrator",
        "observer",
        "seed-strategist",
        "socialDiscovery",
        "socialMonitor",
        "sparrow",
        "strategist",
        "trademarkMonitor"
      ]
    },
    {
      "pattern": "11 */6 * * *",
      "handler_path": "packages/averrow-worker/src/index.ts",
      "agents_invoked": [
        "abuseMailboxClassifier",
        "analyst",
        "appStoreMonitor",
        "attributor",
        "auto-seeder",
        "cartographer",
        "ct-monitor",
        "cube-healer",
        "darkWebMonitor",
        "executiveMonitor",
        "flightControl",
        "geoip-refresh",
        "lookalike-scanner",
        "narrator",
        "news-watcher",
        "nexus",
        "notification_narrator",
        "observer",
        "seed-strategist",
        "socialDiscovery",
        "socialMonitor",
        "sparrow",
        "strategist",
        "trademarkMonitor"
      ]
    },
    {
      "pattern": "13 */6 * * *",
      "handler_path": "packages/averrow-worker/src/index.ts",
      "agents_invoked": [
        "abuseMailboxClassifier",
        "analyst",
        "appStoreMonitor",
        "attributor",
        "auto-seeder",
        "cartographer",
        "ct-monitor",
        "cube-healer",
        "darkWebMonitor",
        "executiveMonitor",
        "flightControl",
        "geoip-refresh",
        "lookalike-scanner",
        "narrator",
        "news-watcher",
        "nexus",
        "notification_narrator",
        "observer",
        "seed-strategist",
        "socialDiscovery",
        "socialMonitor",
        "sparrow",
        "strategist",
        "trademarkMonitor"
      ]
    },
    {
      "pattern": "14 */6 * * *",
      "handler_path": "packages/averrow-worker/src/index.ts",
      "agents_invoked": [
        "abuseMailboxClassifier",
        "analyst",
        "appStoreMonitor",
        "attributor",
        "auto-seeder",
        "cartographer",
        "ct-monitor",
        "cube-healer",
        "darkWebMonitor",
        "executiveMonitor",
        "flightControl",
        "geoip-refresh",
        "lookalike-scanner",
        "narrator",
        "news-watcher",
        "nexus",
        "notification_narrator",
        "observer",
        "seed-strategist",
        "socialDiscovery",
        "socialMonitor",
        "sparrow",
        "strategist",
        "trademarkMonitor"
      ]
    },
    {
      "pattern": "15 */6 * * *",
      "handler_path": "packages/averrow-worker/src/index.ts",
      "agents_invoked": [
        "abuseMailboxClassifier",
        "analyst",
        "appStoreMonitor",
        "attributor",
        "auto-seeder",
        "cartographer",
        "ct-monitor",
        "cube-healer",
        "darkWebMonitor",
        "executiveMonitor",
        "flightControl",
        "geoip-refresh",
        "lookalike-scanner",
        "narrator",
        "news-watcher",
        "nexus",
        "notification_narrator",
        "observer",
        "seed-strategist",
        "socialDiscovery",
        "socialMonitor",
        "sparrow",
        "strategist",
        "trademarkMonitor"
      ]
    },
    {
      "pattern": "16 0 * * *",
      "handler_path": "packages/averrow-worker/src/index.ts",
      "agents_invoked": [
        "abuseMailboxClassifier",
        "analyst",
        "appStoreMonitor",
        "attributor",
        "auto-seeder",
        "cartographer",
        "ct-monitor",
        "cube-healer",
        "darkWebMonitor",
        "executiveMonitor",
        "flightControl",
        "geoip-refresh",
        "lookalike-scanner",
        "narrator",
        "news-watcher",
        "nexus",
        "notification_narrator",
        "observer",
        "seed-strategist",
        "socialDiscovery",
        "socialMonitor",
        "sparrow",
        "strategist",
        "trademarkMonitor"
      ]
    },
    {
      "pattern": "*/5 * * * *",
      "handler_path": "packages/averrow-worker/src/index.ts",
      "agents_invoked": [
        "abuseMailboxClassifier",
        "analyst",
        "appStoreMonitor",
        "attributor",
        "auto-seeder",
        "cartographer",
        "ct-monitor",
        "cube-healer",
        "darkWebMonitor",
        "executiveMonitor",
        "flightControl",
        "geoip-refresh",
        "lookalike-scanner",
        "narrator",
        "news-watcher",
        "nexus",
        "notification_narrator",
        "observer",
        "seed-strategist",
        "socialDiscovery",
        "socialMonitor",
        "sparrow",
        "strategist",
        "trademarkMonitor"
      ]
    },
    {
      "pattern": "12 */6 * * *",
      "handler_path": "packages/averrow-worker/src/index.ts",
      "agents_invoked": [
        "abuseMailboxClassifier",
        "analyst",
        "appStoreMonitor",
        "attributor",
        "auto-seeder",
        "cartographer",
        "ct-monitor",
        "cube-healer",
        "darkWebMonitor",
        "executiveMonitor",
        "flightControl",
        "geoip-refresh",
        "lookalike-scanner",
        "narrator",
        "news-watcher",
        "nexus",
        "notification_narrator",
        "observer",
        "seed-strategist",
        "socialDiscovery",
        "socialMonitor",
        "sparrow",
        "strategist",
        "trademarkMonitor"
      ]
    },
    {
      "pattern": "13 13 * * *",
      "handler_path": "packages/averrow-worker/src/index.ts",
      "agents_invoked": [
        "abuseMailboxClassifier",
        "analyst",
        "appStoreMonitor",
        "attributor",
        "auto-seeder",
        "cartographer",
        "ct-monitor",
        "cube-healer",
        "darkWebMonitor",
        "executiveMonitor",
        "flightControl",
        "geoip-refresh",
        "lookalike-scanner",
        "narrator",
        "news-watcher",
        "nexus",
        "notification_narrator",
        "observer",
        "seed-strategist",
        "socialDiscovery",
        "socialMonitor",
        "sparrow",
        "strategist",
        "trademarkMonitor"
      ]
    },
    {
      "pattern": "17 * * * *",
      "handler_path": "packages/averrow-worker/src/index.ts",
      "agents_invoked": [
        "abuseMailboxClassifier",
        "analyst",
        "appStoreMonitor",
        "attributor",
        "auto-seeder",
        "cartographer",
        "ct-monitor",
        "cube-healer",
        "darkWebMonitor",
        "executiveMonitor",
        "flightControl",
        "geoip-refresh",
        "lookalike-scanner",
        "narrator",
        "news-watcher",
        "nexus",
        "notification_narrator",
        "observer",
        "seed-strategist",
        "socialDiscovery",
        "socialMonitor",
        "sparrow",
        "strategist",
        "trademarkMonitor"
      ]
    },
    {
      "pattern": "18 * * * *",
      "handler_path": "packages/averrow-worker/src/index.ts",
      "agents_invoked": [
        "abuseMailboxClassifier",
        "analyst",
        "appStoreMonitor",
        "attributor",
        "auto-seeder",
        "cartographer",
        "ct-monitor",
        "cube-healer",
        "darkWebMonitor",
        "executiveMonitor",
        "flightControl",
        "geoip-refresh",
        "lookalike-scanner",
        "narrator",
        "news-watcher",
        "nexus",
        "notification_narrator",
        "observer",
        "seed-strategist",
        "socialDiscovery",
        "socialMonitor",
        "sparrow",
        "strategist",
        "trademarkMonitor"
      ]
    },
    {
      "pattern": "19 */4 * * *",
      "handler_path": "packages/averrow-worker/src/index.ts",
      "agents_invoked": [
        "abuseMailboxClassifier",
        "analyst",
        "appStoreMonitor",
        "attributor",
        "auto-seeder",
        "cartographer",
        "ct-monitor",
        "cube-healer",
        "darkWebMonitor",
        "executiveMonitor",
        "flightControl",
        "geoip-refresh",
        "lookalike-scanner",
        "narrator",
        "news-watcher",
        "nexus",
        "notification_narrator",
        "observer",
        "seed-strategist",
        "socialDiscovery",
        "socialMonitor",
        "sparrow",
        "strategist",
        "trademarkMonitor"
      ]
    },
    {
      "pattern": "21 * * * *",
      "handler_path": "packages/averrow-worker/src/index.ts",
      "agents_invoked": [
        "abuseMailboxClassifier",
        "analyst",
        "appStoreMonitor",
        "attributor",
        "auto-seeder",
        "cartographer",
        "ct-monitor",
        "cube-healer",
        "darkWebMonitor",
        "executiveMonitor",
        "flightControl",
        "geoip-refresh",
        "lookalike-scanner",
        "narrator",
        "news-watcher",
        "nexus",
        "notification_narrator",
        "observer",
        "seed-strategist",
        "socialDiscovery",
        "socialMonitor",
        "sparrow",
        "strategist",
        "trademarkMonitor"
      ]
    },
    {
      "pattern": "22 * * * *",
      "handler_path": "packages/averrow-worker/src/index.ts",
      "agents_invoked": [
        "abuseMailboxClassifier",
        "analyst",
        "appStoreMonitor",
        "attributor",
        "auto-seeder",
        "cartographer",
        "ct-monitor",
        "cube-healer",
        "darkWebMonitor",
        "executiveMonitor",
        "flightControl",
        "geoip-refresh",
        "lookalike-scanner",
        "narrator",
        "news-watcher",
        "nexus",
        "notification_narrator",
        "observer",
        "seed-strategist",
        "socialDiscovery",
        "socialMonitor",
        "sparrow",
        "strategist",
        "trademarkMonitor"
      ]
    },
    {
      "pattern": "23 * * * *",
      "handler_path": "packages/averrow-worker/src/index.ts",
      "agents_invoked": [
        "abuseMailboxClassifier",
        "analyst",
        "appStoreMonitor",
        "attributor",
        "auto-seeder",
        "cartographer",
        "ct-monitor",
        "cube-healer",
        "darkWebMonitor",
        "executiveMonitor",
        "flightControl",
        "geoip-refresh",
        "lookalike-scanner",
        "narrator",
        "news-watcher",
        "nexus",
        "notification_narrator",
        "observer",
        "seed-strategist",
        "socialDiscovery",
        "socialMonitor",
        "sparrow",
        "strategist",
        "trademarkMonitor"
      ]
    },
    {
      "pattern": "26 */6 * * *",
      "handler_path": "packages/averrow-worker/src/index.ts",
      "agents_invoked": [
        "abuseMailboxClassifier",
        "analyst",
        "appStoreMonitor",
        "attributor",
        "auto-seeder",
        "cartographer",
        "ct-monitor",
        "cube-healer",
        "darkWebMonitor",
        "executiveMonitor",
        "flightControl",
        "geoip-refresh",
        "lookalike-scanner",
        "narrator",
        "news-watcher",
        "nexus",
        "notification_narrator",
        "observer",
        "seed-strategist",
        "socialDiscovery",
        "socialMonitor",
        "sparrow",
        "strategist",
        "trademarkMonitor"
      ]
    },
    {
      "pattern": "24 14 * * 1",
      "handler_path": "packages/averrow-worker/src/index.ts",
      "agents_invoked": [
        "abuseMailboxClassifier",
        "analyst",
        "appStoreMonitor",
        "attributor",
        "auto-seeder",
        "cartographer",
        "ct-monitor",
        "cube-healer",
        "darkWebMonitor",
        "executiveMonitor",
        "flightControl",
        "geoip-refresh",
        "lookalike-scanner",
        "narrator",
        "news-watcher",
        "nexus",
        "notification_narrator",
        "observer",
        "seed-strategist",
        "socialDiscovery",
        "socialMonitor",
        "sparrow",
        "strategist",
        "trademarkMonitor"
      ]
    }
  ],
  "workers": [
    {
      "name": "averrow-worker",
      "path": "packages/averrow-worker/src/index.ts",
      "bindings": [
        "ARCHITECT_BUNDLES",
        "AUDIT_DB",
        "CACHE",
        "CAMPAIGN_HUNTER",
        "CARTOGRAPHER_BACKFILL",
        "CARTOGRAPHER_MAIN",
        "CERTSTREAM_MONITOR",
        "DB",
        "DNS_QUEUE_DB",
        "GEOIP_DB",
        "GEOIP_REFRESH",
        "GEOIP_STAGING",
        "NEXUS_RUN",
        "THREAT_PUSH_HUB",
        "TRADEMARK_ASSETS"
      ]
    }
  ],
  "totals": {
    "agents": 43,
    "feeds": 50,
    "crons": 20,
    "workers": 1
  }
};
