#!/usr/bin/env tsx
/**
 * Build-time ARCHITECT repo manifest generator.
 *
 * Walks the monorepo with the Node fs collector and emits
 * src/agents/architect/manifest.generated.ts — a deterministic
 * RepoInventory snapshot that the Worker imports at runtime (Workers
 * have no filesystem, so a live walk is impossible in-request).
 *
 * Wired into the trust-radar build script so every `pnpm build` /
 * `pnpm deploy:radar` (via turbo) refreshes the manifest before wrangler
 * compiles the Worker bundle. The generated file is committed to git so
 * downstream tooling and code review can see inventory drift.
 *
 * Usage:
 *   pnpm --filter trust-radar build:manifest
 *   tsx scripts/build-architect-manifest.ts
 */

import { writeFile } from "node:fs/promises";
import { resolve } from "node:path";

import { collectRepoInventoryFromFs } from "../src/agents/architect/collectors/repo-fs";
import type { RepoInventory } from "../src/agents/architect/types";

async function main(): Promise<void> {
  // This file lives at packages/trust-radar/scripts/. The package dir
  // is one level up; the monorepo root is two more levels up from that.
  const packageDir = resolve(__dirname, "..");
  const monorepoRoot = resolve(packageDir, "..", "..");

  const manifest = await collectRepoInventoryFromFs(monorepoRoot);

  const outPath = resolve(
    packageDir,
    "src",
    "agents",
    "architect",
    "manifest.generated.ts",
  );

  const source = renderManifestModule(manifest);
  await writeFile(outPath, source, "utf8");

  console.log(
    `[architect-manifest] wrote ${outPath} ` +
      `agents=${manifest.totals.agents} ` +
      `feeds=${manifest.totals.feeds} ` +
      `crons=${manifest.totals.crons} ` +
      `workers=${manifest.totals.workers}`,
  );
}

function renderManifestModule(manifest: RepoInventory): string {
  // Zero the collected_at timestamp so build output stays deterministic
  // between runs on unchanged source — git noise otherwise. The real
  // "when was this bundle produced" signal lives on architect_reports
  // and ContextBundle.generated_at, not inside the inventory.
  const stable: RepoInventory = { ...manifest, collected_at: "build-time" };
  const json = JSON.stringify(stable, null, 2);

  return (
    `/**\n` +
    ` * ARCHITECT repo manifest — GENERATED FILE. DO NOT EDIT BY HAND.\n` +
    ` *\n` +
    ` * Regenerated by scripts/build-architect-manifest.ts on every\n` +
    ` * trust-radar build. Committed to git so the Worker has a\n` +
    ` * deterministic repo inventory at runtime without filesystem access.\n` +
    ` */\n\n` +
    `import type { RepoInventory } from "./types";\n\n` +
    `export const REPO_MANIFEST: RepoInventory = ${json};\n`
  );
}

main().catch((err) => {
  console.error("[architect-manifest] failed:", err);
  process.exit(1);
});
